// Code generated by axe on 2026-04-19. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/internal/handler"
)

type mockBookmarkSvc struct{}

func (m *mockBookmarkSvc) CreateBookmark(_ context.Context, _ domain.CreateBookmarkInput) (*domain.Bookmark, error) {
	return &domain.Bookmark{ID: uuid.New()}, nil
}
func (m *mockBookmarkSvc) GetBookmark(_ context.Context, id uuid.UUID) (*domain.Bookmark, error) {
	return &domain.Bookmark{ID: id}, nil
}
func (m *mockBookmarkSvc) UpdateBookmark(_ context.Context, id uuid.UUID, _ domain.UpdateBookmarkInput) (*domain.Bookmark, error) {
	return &domain.Bookmark{ID: id}, nil
}
func (m *mockBookmarkSvc) DeleteBookmark(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockBookmarkSvc) ListBookmarks(_ context.Context, _ domain.Pagination) ([]*domain.Bookmark, int, error) {
	return []*domain.Bookmark{}, 0, nil
}

// setupBookmarkRouter mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setupBookmarkRouter() *chi.Mux {
	h := handler.NewBookmarkHandler(&mockBookmarkSvc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/bookmarks/{id}", h.GetBookmark)
	r.Put("/api/v1/bookmarks/{id}", h.UpdateBookmark)
	r.Delete("/api/v1/bookmarks/{id}", h.DeleteBookmark)
	r.Get("/api/v1/bookmarks", h.ListBookmarks)
	r.Post("/api/v1/bookmarks", h.CreateBookmark)
	return r
}

func TestBookmark_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/bookmarks/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupBookmarkRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestBookmark_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/bookmarks/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupBookmarkRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestBookmark_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/bookmarks", nil)
	rec := httptest.NewRecorder()
	setupBookmarkRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
