// Code generated by axe on 2026-04-19. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/internal/handler"
)

type mockEpisodeSvc struct{}

func (m *mockEpisodeSvc) CreateEpisode(_ context.Context, _ domain.CreateEpisodeInput) (*domain.Episode, error) {
	return &domain.Episode{ID: uuid.New()}, nil
}
func (m *mockEpisodeSvc) GetEpisode(_ context.Context, id uuid.UUID) (*domain.Episode, error) {
	return &domain.Episode{ID: id}, nil
}
func (m *mockEpisodeSvc) UpdateEpisode(_ context.Context, id uuid.UUID, _ domain.UpdateEpisodeInput) (*domain.Episode, error) {
	return &domain.Episode{ID: id}, nil
}
func (m *mockEpisodeSvc) DeleteEpisode(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockEpisodeSvc) ListEpisodes(_ context.Context, _ domain.Pagination) ([]*domain.Episode, int, error) {
	return []*domain.Episode{}, 0, nil
}
func (m *mockEpisodeSvc) ListEpisodesBySeries(_ context.Context, _ uuid.UUID, _ domain.Pagination) ([]*domain.Episode, int, error) {
	return []*domain.Episode{}, 0, nil
}

// setupEpisodeRouter mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setupEpisodeRouter() *chi.Mux {
	h := handler.NewEpisodeHandler(&mockEpisodeSvc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/episodes/{id}", h.GetEpisode)
	r.Put("/api/v1/episodes/{id}", h.UpdateEpisode)
	r.Delete("/api/v1/episodes/{id}", h.DeleteEpisode)
	r.Get("/api/v1/episodes", h.ListEpisodes)
	r.Post("/api/v1/episodes", h.CreateEpisode)
	return r
}

func TestEpisode_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/episodes/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupEpisodeRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestEpisode_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/episodes/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupEpisodeRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestEpisode_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/episodes", nil)
	rec := httptest.NewRecorder()
	setupEpisodeRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
