// Code generated by axe on 2026-04-19. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/internal/handler/middleware"
	"github.com/axe-cute/examples-webtoon/pkg/apperror"
	"github.com/axe-cute/examples-webtoon/pkg/jwtauth"
)

// EpisodeHandler handles HTTP requests for the Episode domain.
type EpisodeHandler struct {
	svc domain.EpisodeService
	jwtSvc   *jwtauth.Service   // required: set via WithJWTAuth option
	blocklist middleware.Blocklist
}

// NewEpisodeHandler creates a new EpisodeHandler.
func NewEpisodeHandler(svc domain.EpisodeService) *EpisodeHandler {
	return &EpisodeHandler{svc: svc}
}

// WithJWTAuth sets the JWT service and optional blocklist for route protection.
// Call before registering routes:
//
//	h := handler.NewEpisodeHandler(svc).WithJWTAuth(jwtSvc, cacheClient)
func (h *EpisodeHandler) WithJWTAuth(svc *jwtauth.Service, bl middleware.Blocklist) *EpisodeHandler {
	h.jwtSvc = svc
	h.blocklist = bl
	return h
}


// Routes returns a Chi router with all episode endpoints.
// Register in main.go: r.Mount("/api/v1/episodes", episodeHandler.Routes())
func (h *EpisodeHandler) Routes() chi.Router {
	r := chi.NewRouter()
	// Authentication required for all episode routes
	r.Use(middleware.JWTAuth(h.jwtSvc, h.blocklist))
	r.Post("/", h.CreateEpisode)
	r.Get("/", h.ListEpisodes)
	r.Get("/{id}", h.GetEpisode)
	r.Put("/{id}", h.UpdateEpisode)
	r.Delete("/{id}", h.DeleteEpisode)
	return r
}

// createEpisodeRequest is the POST request body.
type createEpisodeRequest struct {
	Title string `json:"title"`
	EpisodeNumber int64 `json:"episode_number"`
	ThumbnailUrl string `json:"thumbnail_url"`
	Published bool `json:"published"`
}

// episodeResponse is the API response shape.
type episodeResponse struct {
	ID        string `json:"id"`
	Title string `json:"title"`
	EpisodeNumber int64 `json:"episode_number"`
	ThumbnailUrl string `json:"thumbnail_url"`
	Published bool `json:"published"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func toEpisodeResponse(e *domain.Episode) *episodeResponse {
	return &episodeResponse{
		ID: e.ID.String(),
		Title: e.Title,
		EpisodeNumber: e.EpisodeNumber,
		ThumbnailUrl: e.ThumbnailUrl,
		Published: e.Published,
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *EpisodeHandler) CreateEpisode(w http.ResponseWriter, r *http.Request) {
	var req createEpisodeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.CreateEpisode(r.Context(), domain.CreateEpisodeInput{
		Title: req.Title,
		EpisodeNumber: req.EpisodeNumber,
		ThumbnailUrl: req.ThumbnailUrl,
		Published: req.Published,
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toEpisodeResponse(result))
}

func (h *EpisodeHandler) GetEpisode(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.GetEpisode(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toEpisodeResponse(result))
}

func (h *EpisodeHandler) UpdateEpisode(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.UpdateEpisodeInput
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.UpdateEpisode(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toEpisodeResponse(result))
}

func (h *EpisodeHandler) DeleteEpisode(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.DeleteEpisode(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *EpisodeHandler) ListEpisodes(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.ListEpisodes(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*episodeResponse, len(results))
	for i, e := range results {
		data[i] = toEpisodeResponse(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
