// Code generated by axe on 2026-04-19. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/internal/handler/middleware"
	"github.com/axe-cute/examples-webtoon/pkg/apperror"
	"github.com/axe-cute/examples-webtoon/pkg/jwtauth"
)

// SeriesHandler handles HTTP requests for the Series domain.
type SeriesHandler struct {
	svc       domain.SeriesService
	jwtSvc    *jwtauth.Service // required: set via WithJWTAuth option
	blocklist middleware.Blocklist
}

// NewSeriesHandler creates a new SeriesHandler.
func NewSeriesHandler(svc domain.SeriesService) *SeriesHandler {
	return &SeriesHandler{svc: svc}
}

// WithJWTAuth sets the JWT service and optional blocklist for route protection.
// Call before registering routes:
//
//	h := handler.NewSeriesHandler(svc).WithJWTAuth(jwtSvc, cacheClient)
func (h *SeriesHandler) WithJWTAuth(svc *jwtauth.Service, bl middleware.Blocklist) *SeriesHandler {
	h.jwtSvc = svc
	h.blocklist = bl
	return h
}

// Routes returns a Chi router with all series endpoints.
// Register in main.go: r.Mount("/api/v1/serieses", seriesHandler.Routes())
func (h *SeriesHandler) Routes() chi.Router {
	r := chi.NewRouter()
	// Authentication required for all series routes
	r.Use(middleware.JWTAuth(h.jwtSvc, h.blocklist))
	r.Post("/", h.CreateSeries)
	r.Get("/", h.ListSeriess)
	r.Get("/{id}", h.GetSeries)
	r.Put("/{id}", h.UpdateSeries)
	r.Delete("/{id}", h.DeleteSeries)
	return r
}

// createSeriesRequest is the POST request body.
type createSeriesRequest struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Genre       string `json:"genre"`
	Author      string `json:"author"`
	CoverUrl    string `json:"cover_url"`
	Status      string `json:"status"`
}

// seriesResponse is the API response shape.
type seriesResponse struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Genre       string `json:"genre"`
	Author      string `json:"author"`
	CoverUrl    string `json:"cover_url"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func toSeriesResponse(e *domain.Series) *seriesResponse {
	return &seriesResponse{
		ID:          e.ID.String(),
		Title:       e.Title,
		Description: e.Description,
		Genre:       e.Genre,
		Author:      e.Author,
		CoverUrl:    e.CoverUrl,
		Status:      e.Status,
		CreatedAt:   e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:   e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *SeriesHandler) CreateSeries(w http.ResponseWriter, r *http.Request) {
	var req createSeriesRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.CreateSeries(r.Context(), domain.CreateSeriesInput{
		Title:       req.Title,
		Description: req.Description,
		Genre:       req.Genre,
		Author:      req.Author,
		CoverUrl:    req.CoverUrl,
		Status:      req.Status,
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toSeriesResponse(result))
}

func (h *SeriesHandler) GetSeries(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.GetSeries(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toSeriesResponse(result))
}

func (h *SeriesHandler) UpdateSeries(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.UpdateSeriesInput
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.UpdateSeries(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toSeriesResponse(result))
}

func (h *SeriesHandler) DeleteSeries(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.DeleteSeries(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *SeriesHandler) ListSeriess(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.ListSeriess(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*seriesResponse, len(results))
	for i, e := range results {
		data[i] = toSeriesResponse(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
