// Code generated by axe on 2026-04-19. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/internal/handler"
)

type mockSeriesSvc struct{}

func (m *mockSeriesSvc) CreateSeries(_ context.Context, _ domain.CreateSeriesInput) (*domain.Series, error) {
	return &domain.Series{ID: uuid.New()}, nil
}
func (m *mockSeriesSvc) GetSeries(_ context.Context, id uuid.UUID) (*domain.Series, error) {
	return &domain.Series{ID: id}, nil
}
func (m *mockSeriesSvc) UpdateSeries(_ context.Context, id uuid.UUID, _ domain.UpdateSeriesInput) (*domain.Series, error) {
	return &domain.Series{ID: id}, nil
}
func (m *mockSeriesSvc) DeleteSeries(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockSeriesSvc) ListSeriess(_ context.Context, _ domain.Pagination) ([]*domain.Series, int, error) {
	return []*domain.Series{}, 0, nil
}

// setupSeriesRouter mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setupSeriesRouter() *chi.Mux {
	h := handler.NewSeriesHandler(&mockSeriesSvc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/serieses/{id}", h.GetSeries)
	r.Put("/api/v1/serieses/{id}", h.UpdateSeries)
	r.Delete("/api/v1/serieses/{id}", h.DeleteSeries)
	r.Get("/api/v1/serieses", h.ListSeriess)
	r.Post("/api/v1/serieses", h.CreateSeries)
	return r
}

func TestSeries_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/serieses/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupSeriesRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestSeries_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/serieses/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupSeriesRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestSeries_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/serieses", nil)
	rec := httptest.NewRecorder()
	setupSeriesRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
