// Code generated by axe on 2026-04-19. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Bookmark represents a user's bookmarked (favorited) series.
type Bookmark struct {
	ID        uuid.UUID
	UserID    string    // from JWT claims
	SeriesID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// BookmarkRepository defines data access for Bookmark.
// Implemented in internal/repository/bookmark_repo.go.
type BookmarkRepository interface {
	Create(ctx context.Context, input CreateBookmarkInput) (*Bookmark, error)
	Update(ctx context.Context, id uuid.UUID, input UpdateBookmarkInput) (*Bookmark, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Bookmark, error)
	List(ctx context.Context, pagination Pagination) ([]*Bookmark, int, error)
}

// BookmarkService defines business operations for Bookmark.
// Implemented in internal/service/bookmark_service.go.
type BookmarkService interface {
	CreateBookmark(ctx context.Context, input CreateBookmarkInput) (*Bookmark, error)
	GetBookmark(ctx context.Context, id uuid.UUID) (*Bookmark, error)
	UpdateBookmark(ctx context.Context, id uuid.UUID, input UpdateBookmarkInput) (*Bookmark, error)
	DeleteBookmark(ctx context.Context, id uuid.UUID) error
	ListBookmarks(ctx context.Context, pagination Pagination) ([]*Bookmark, int, error)

	// ToggleBookmark adds or removes a bookmark. Returns the bookmark state.
	ToggleBookmark(ctx context.Context, userID string, seriesID uuid.UUID) (*ToggleResult, error)
}

// ToggleResult indicates whether a bookmark was added or removed.
type ToggleResult struct {
	Bookmarked bool      `json:"bookmarked"`
	SeriesID   uuid.UUID `json:"series_id"`
}

// CreateBookmarkInput holds fields required to create a Bookmark.
type CreateBookmarkInput struct {
	UserID   string
	SeriesID uuid.UUID
}

// UpdateBookmarkInput holds optional fields for partial update.
type UpdateBookmarkInput struct {
	SeriesID *uuid.UUID `json:"series_id,omitempty"`
}
