// Code generated by axe on 2026-04-19. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Episode is the Episode domain entity.
type Episode struct {
	ID            uuid.UUID
	Title         string
	EpisodeNumber int64
	ThumbnailUrl  string
	Published     bool
	ViewCount     int64 // auto-incremented on read
	SeriesID      uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// EpisodeRepository defines data access for Episode.
// Implemented in internal/repository/episode_repo.go.
type EpisodeRepository interface {
	Create(ctx context.Context, input CreateEpisodeInput) (*Episode, error)
	Update(ctx context.Context, id uuid.UUID, input UpdateEpisodeInput) (*Episode, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Episode, error)
	List(ctx context.Context, pagination Pagination) ([]*Episode, int, error)
}

// EpisodeService defines business operations for Episode.
// Implemented in internal/service/episode_service.go.
type EpisodeService interface {
	CreateEpisode(ctx context.Context, input CreateEpisodeInput) (*Episode, error)
	GetEpisode(ctx context.Context, id uuid.UUID) (*Episode, error)
	UpdateEpisode(ctx context.Context, id uuid.UUID, input UpdateEpisodeInput) (*Episode, error)
	DeleteEpisode(ctx context.Context, id uuid.UUID) error
	ListEpisodes(ctx context.Context, pagination Pagination) ([]*Episode, int, error)
}

// CreateEpisodeInput holds fields required to create a Episode.
type CreateEpisodeInput struct {
	Title         string
	EpisodeNumber int64
	ThumbnailUrl  string
	Published     bool
	SeriesID      uuid.UUID
}

// UpdateEpisodeInput holds optional fields for partial update.
type UpdateEpisodeInput struct {
	Title         *string `json:"title,omitempty"`
	EpisodeNumber *int64  `json:"episode_number,omitempty"`
	ThumbnailUrl  *string `json:"thumbnail_url,omitempty"`
	Published     *bool   `json:"published,omitempty"`
}
