// Code generated by axe on 2026-04-19. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Series is the Series domain entity.
type Series struct {
	ID uuid.UUID
	Title string
	Description string
	Genre string
	Author string
	CoverUrl string
	Status string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// SeriesRepository defines data access for Series.
// Implemented in internal/repository/series_repo.go.
type SeriesRepository interface {
	Create(ctx context.Context, input CreateSeriesInput) (*Series, error)
	Update(ctx context.Context, id uuid.UUID, input UpdateSeriesInput) (*Series, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Series, error)
	List(ctx context.Context, pagination Pagination) ([]*Series, int, error)
}

// SeriesService defines business operations for Series.
// Implemented in internal/service/series_service.go.
type SeriesService interface {
	CreateSeries(ctx context.Context, input CreateSeriesInput) (*Series, error)
	GetSeries(ctx context.Context, id uuid.UUID) (*Series, error)
	UpdateSeries(ctx context.Context, id uuid.UUID, input UpdateSeriesInput) (*Series, error)
	DeleteSeries(ctx context.Context, id uuid.UUID) error
	ListSeriess(ctx context.Context, pagination Pagination) ([]*Series, int, error)
}

// CreateSeriesInput holds fields required to create a Series.
type CreateSeriesInput struct {
	Title string
	Description string
	Genre string
	Author string
	CoverUrl string
	Status string
}

// UpdateSeriesInput holds optional fields for partial update.
type UpdateSeriesInput struct {
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Genre *string `json:"genre,omitempty"`
	Author *string `json:"author,omitempty"`
	CoverUrl *string `json:"cover_url,omitempty"`
	Status *string `json:"status,omitempty"`
}
