// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/axe-cute/examples-webtoon/ent/episode"
	"github.com/axe-cute/examples-webtoon/ent/predicate"
	"github.com/google/uuid"
)

// EpisodeUpdate is the builder for updating Episode entities.
type EpisodeUpdate struct {
	config
	hooks    []Hook
	mutation *EpisodeMutation
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (_u *EpisodeUpdate) Where(ps ...predicate.Episode) *EpisodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *EpisodeUpdate) SetTitle(v string) *EpisodeUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableTitle(v *string) *EpisodeUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetEpisodeNumber sets the "episode_number" field.
func (_u *EpisodeUpdate) SetEpisodeNumber(v int64) *EpisodeUpdate {
	_u.mutation.ResetEpisodeNumber()
	_u.mutation.SetEpisodeNumber(v)
	return _u
}

// SetNillableEpisodeNumber sets the "episode_number" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableEpisodeNumber(v *int64) *EpisodeUpdate {
	if v != nil {
		_u.SetEpisodeNumber(*v)
	}
	return _u
}

// AddEpisodeNumber adds value to the "episode_number" field.
func (_u *EpisodeUpdate) AddEpisodeNumber(v int64) *EpisodeUpdate {
	_u.mutation.AddEpisodeNumber(v)
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *EpisodeUpdate) SetThumbnailURL(v string) *EpisodeUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableThumbnailURL(v *string) *EpisodeUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// SetPublished sets the "published" field.
func (_u *EpisodeUpdate) SetPublished(v bool) *EpisodeUpdate {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillablePublished(v *bool) *EpisodeUpdate {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *EpisodeUpdate) SetSeriesID(v uuid.UUID) *EpisodeUpdate {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableSeriesID(v *uuid.UUID) *EpisodeUpdate {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EpisodeUpdate) SetUpdatedAt(v time.Time) *EpisodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EpisodeMutation object of the builder.
func (_u *EpisodeUpdate) Mutation() *EpisodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EpisodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EpisodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EpisodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EpisodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EpisodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := episode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *EpisodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.EpisodeNumber(); ok {
		_spec.SetField(episode.FieldEpisodeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEpisodeNumber(); ok {
		_spec.AddField(episode.FieldEpisodeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(episode.FieldThumbnailURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(episode.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SeriesID(); ok {
		_spec.SetField(episode.FieldSeriesID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(episode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EpisodeUpdateOne is the builder for updating a single Episode entity.
type EpisodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EpisodeMutation
}

// SetTitle sets the "title" field.
func (_u *EpisodeUpdateOne) SetTitle(v string) *EpisodeUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableTitle(v *string) *EpisodeUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetEpisodeNumber sets the "episode_number" field.
func (_u *EpisodeUpdateOne) SetEpisodeNumber(v int64) *EpisodeUpdateOne {
	_u.mutation.ResetEpisodeNumber()
	_u.mutation.SetEpisodeNumber(v)
	return _u
}

// SetNillableEpisodeNumber sets the "episode_number" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableEpisodeNumber(v *int64) *EpisodeUpdateOne {
	if v != nil {
		_u.SetEpisodeNumber(*v)
	}
	return _u
}

// AddEpisodeNumber adds value to the "episode_number" field.
func (_u *EpisodeUpdateOne) AddEpisodeNumber(v int64) *EpisodeUpdateOne {
	_u.mutation.AddEpisodeNumber(v)
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *EpisodeUpdateOne) SetThumbnailURL(v string) *EpisodeUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableThumbnailURL(v *string) *EpisodeUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// SetPublished sets the "published" field.
func (_u *EpisodeUpdateOne) SetPublished(v bool) *EpisodeUpdateOne {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillablePublished(v *bool) *EpisodeUpdateOne {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *EpisodeUpdateOne) SetSeriesID(v uuid.UUID) *EpisodeUpdateOne {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableSeriesID(v *uuid.UUID) *EpisodeUpdateOne {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EpisodeUpdateOne) SetUpdatedAt(v time.Time) *EpisodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EpisodeMutation object of the builder.
func (_u *EpisodeUpdateOne) Mutation() *EpisodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (_u *EpisodeUpdateOne) Where(ps ...predicate.Episode) *EpisodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EpisodeUpdateOne) Select(field string, fields ...string) *EpisodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Episode entity.
func (_u *EpisodeUpdateOne) Save(ctx context.Context) (*Episode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EpisodeUpdateOne) SaveX(ctx context.Context) *Episode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EpisodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EpisodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EpisodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := episode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *EpisodeUpdateOne) sqlSave(ctx context.Context) (_node *Episode, err error) {
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Episode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, episode.FieldID)
		for _, f := range fields {
			if !episode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != episode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.EpisodeNumber(); ok {
		_spec.SetField(episode.FieldEpisodeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEpisodeNumber(); ok {
		_spec.AddField(episode.FieldEpisodeNumber, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(episode.FieldThumbnailURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(episode.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SeriesID(); ok {
		_spec.SetField(episode.FieldSeriesID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(episode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Episode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
