// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/axe-cute/examples-webtoon/ent/bookmark"
	"github.com/axe-cute/examples-webtoon/ent/episode"
	"github.com/axe-cute/examples-webtoon/ent/schema"
	"github.com/axe-cute/examples-webtoon/ent/series"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookmarkFields := schema.Bookmark{}.Fields()
	_ = bookmarkFields
	// bookmarkDescCreatedAt is the schema descriptor for created_at field.
	bookmarkDescCreatedAt := bookmarkFields[2].Descriptor()
	// bookmark.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookmark.DefaultCreatedAt = bookmarkDescCreatedAt.Default.(func() time.Time)
	// bookmarkDescUpdatedAt is the schema descriptor for updated_at field.
	bookmarkDescUpdatedAt := bookmarkFields[3].Descriptor()
	// bookmark.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bookmark.DefaultUpdatedAt = bookmarkDescUpdatedAt.Default.(func() time.Time)
	// bookmark.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bookmark.UpdateDefaultUpdatedAt = bookmarkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookmarkDescID is the schema descriptor for id field.
	bookmarkDescID := bookmarkFields[0].Descriptor()
	// bookmark.DefaultID holds the default value on creation for the id field.
	bookmark.DefaultID = bookmarkDescID.Default.(func() uuid.UUID)
	episodeFields := schema.Episode{}.Fields()
	_ = episodeFields
	// episodeDescCreatedAt is the schema descriptor for created_at field.
	episodeDescCreatedAt := episodeFields[6].Descriptor()
	// episode.DefaultCreatedAt holds the default value on creation for the created_at field.
	episode.DefaultCreatedAt = episodeDescCreatedAt.Default.(func() time.Time)
	// episodeDescUpdatedAt is the schema descriptor for updated_at field.
	episodeDescUpdatedAt := episodeFields[7].Descriptor()
	// episode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	episode.DefaultUpdatedAt = episodeDescUpdatedAt.Default.(func() time.Time)
	// episode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	episode.UpdateDefaultUpdatedAt = episodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// episodeDescID is the schema descriptor for id field.
	episodeDescID := episodeFields[0].Descriptor()
	// episode.DefaultID holds the default value on creation for the id field.
	episode.DefaultID = episodeDescID.Default.(func() uuid.UUID)
	seriesFields := schema.Series{}.Fields()
	_ = seriesFields
	// seriesDescCreatedAt is the schema descriptor for created_at field.
	seriesDescCreatedAt := seriesFields[7].Descriptor()
	// series.DefaultCreatedAt holds the default value on creation for the created_at field.
	series.DefaultCreatedAt = seriesDescCreatedAt.Default.(func() time.Time)
	// seriesDescUpdatedAt is the schema descriptor for updated_at field.
	seriesDescUpdatedAt := seriesFields[8].Descriptor()
	// series.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	series.DefaultUpdatedAt = seriesDescUpdatedAt.Default.(func() time.Time)
	// series.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	series.UpdateDefaultUpdatedAt = seriesDescUpdatedAt.UpdateDefault.(func() time.Time)
	// seriesDescID is the schema descriptor for id field.
	seriesDescID := seriesFields[0].Descriptor()
	// series.DefaultID holds the default value on creation for the id field.
	series.DefaultID = seriesDescID.Default.(func() uuid.UUID)
}
