// Code generated by axe on 2026-04-15. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-go/axe/internal/domain"
	"github.com/axe-go/axe/internal/handler"
)

type mockPostSvc struct{}

func (m *mockPostSvc) CreatePost(_ context.Context, _ domain.CreatePostInput) (*domain.Post, error) {
	return &domain.Post{ID: uuid.New()}, nil
}
func (m *mockPostSvc) GetPost(_ context.Context, id uuid.UUID) (*domain.Post, error) {
	return &domain.Post{ID: id}, nil
}
func (m *mockPostSvc) UpdatePost(_ context.Context, id uuid.UUID, _ domain.UpdatePostInput) (*domain.Post, error) {
	return &domain.Post{ID: id}, nil
}
func (m *mockPostSvc) DeletePost(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockPostSvc) ListPosts(_ context.Context, _ domain.Pagination) ([]*domain.Post, int, error) {
	return []*domain.Post{}, 0, nil
}

func setupPostRouter() *chi.Mux {
	h := handler.NewPostHandler(&mockPostSvc{})
	r := chi.NewRouter()
	r.Mount("/api/v1/posts", h.Routes())
	return r
}

func TestPost_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/posts/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupPostRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestPost_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/posts/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupPostRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestPost_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/posts", nil)
	rec := httptest.NewRecorder()
	setupPostRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
