// Code generated by axe on 2026-04-15. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-go/axe/internal/domain"
	"github.com/axe-go/axe/internal/handler/middleware"
	"github.com/axe-go/axe/pkg/apperror"
)

// PostHandler handles HTTP requests for the Post domain.
type PostHandler struct {
	svc domain.PostService
}

// NewPostHandler creates a new PostHandler.
func NewPostHandler(svc domain.PostService) *PostHandler {
	return &PostHandler{svc: svc}
}

// Routes returns a Chi router with all post endpoints.
// Register in main.go: r.Mount("/api/v1/posts", postHandler.Routes())
func (h *PostHandler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Post("/", h.CreatePost)
	r.Get("/", h.ListPosts)
	r.Get("/{id}", h.GetPost)
	r.Put("/{id}", h.UpdatePost)
	r.Delete("/{id}", h.DeletePost)
	return r
}

// createPostRequest is the POST request body.
// TODO: add json struct tags after generation.
type createPostRequest struct {
	Title string
	Body string
	Published bool
	Views int64
}

// postResponse is the API response shape.
// TODO: add json struct tags after generation.
type postResponse struct {
	ID        string
	Title string
	Body string
	Published bool
	Views int64
	CreatedAt string
	UpdatedAt string
}

func toPostResponse(e *domain.Post) *postResponse {
	return &postResponse{
		ID: e.ID.String(),
		Title: e.Title,
		Body: e.Body,
		Published: e.Published,
		Views: e.Views,
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *PostHandler) CreatePost(w http.ResponseWriter, r *http.Request) {
	var req createPostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.CreatePost(r.Context(), domain.CreatePostInput{
		Title: req.Title,
		Body: req.Body,
		Published: req.Published,
		Views: req.Views,
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toPostResponse(result))
}

func (h *PostHandler) GetPost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.GetPost(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toPostResponse(result))
}

func (h *PostHandler) UpdatePost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.UpdatePostInput
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.UpdatePost(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toPostResponse(result))
}

func (h *PostHandler) DeletePost(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.DeletePost(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *PostHandler) ListPosts(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.ListPosts(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*postResponse, len(results))
	for i, e := range results {
		data[i] = toPostResponse(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
