// Code generated by axe on 2026-04-19. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Order is the Order domain entity.
type Order struct {
	ID uuid.UUID
	Total float64
	Status string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// OrderRepository defines data access for Order.
// Implemented in internal/repository/order_repo.go.
type OrderRepository interface {
	Create(ctx context.Context, input CreateOrderInput) (*Order, error)
	Update(ctx context.Context, id uuid.UUID, input UpdateOrderInput) (*Order, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Order, error)
	List(ctx context.Context, pagination Pagination) ([]*Order, int, error)
}

// OrderService defines business operations for Order.
// Implemented in internal/service/order_service.go.
type OrderService interface {
	CreateOrder(ctx context.Context, input CreateOrderInput) (*Order, error)
	GetOrder(ctx context.Context, id uuid.UUID) (*Order, error)
	UpdateOrder(ctx context.Context, id uuid.UUID, input UpdateOrderInput) (*Order, error)
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	ListOrders(ctx context.Context, pagination Pagination) ([]*Order, int, error)
}

// CreateOrderInput holds fields required to create a Order.
type CreateOrderInput struct {
	Total float64
	Status string
}

// UpdateOrderInput holds optional fields for partial update.
type UpdateOrderInput struct {
	Total *float64 `json:"total,omitempty"`
	Status *string `json:"status,omitempty"`
}
