// Code generated by axe on 2026-04-19. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Product is the Product domain entity.
type Product struct {
	ID uuid.UUID
	Name string
	Description string
	Price float64
	Stock int64
	ImageUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// ProductRepository defines data access for Product.
// Implemented in internal/repository/product_repo.go.
type ProductRepository interface {
	Create(ctx context.Context, input CreateProductInput) (*Product, error)
	Update(ctx context.Context, id uuid.UUID, input UpdateProductInput) (*Product, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Product, error)
	List(ctx context.Context, pagination Pagination) ([]*Product, int, error)
}

// ProductService defines business operations for Product.
// Implemented in internal/service/product_service.go.
type ProductService interface {
	CreateProduct(ctx context.Context, input CreateProductInput) (*Product, error)
	GetProduct(ctx context.Context, id uuid.UUID) (*Product, error)
	UpdateProduct(ctx context.Context, id uuid.UUID, input UpdateProductInput) (*Product, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	ListProducts(ctx context.Context, pagination Pagination) ([]*Product, int, error)
}

// CreateProductInput holds fields required to create a Product.
type CreateProductInput struct {
	Name string
	Description string
	Price float64
	Stock int64
	ImageUrl string
}

// UpdateProductInput holds optional fields for partial update.
type UpdateProductInput struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Price *float64 `json:"price,omitempty"`
	Stock *int64 `json:"stock,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
}
