// Code generated by axe on 2026-04-19. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Review is the Review domain entity.
type Review struct {
	ID        uuid.UUID
	Body      string
	Rating    int64
	ProductID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// ReviewRepository defines data access for Review.
// Implemented in internal/repository/review_repo.go.
type ReviewRepository interface {
	Create(ctx context.Context, input CreateReviewInput) (*Review, error)
	Update(ctx context.Context, id uuid.UUID, input UpdateReviewInput) (*Review, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Review, error)
	List(ctx context.Context, pagination Pagination) ([]*Review, int, error)
}

// ReviewService defines business operations for Review.
// Implemented in internal/service/review_service.go.
type ReviewService interface {
	CreateReview(ctx context.Context, input CreateReviewInput) (*Review, error)
	GetReview(ctx context.Context, id uuid.UUID) (*Review, error)
	UpdateReview(ctx context.Context, id uuid.UUID, input UpdateReviewInput) (*Review, error)
	DeleteReview(ctx context.Context, id uuid.UUID) error
	ListReviews(ctx context.Context, pagination Pagination) ([]*Review, int, error)
}

// CreateReviewInput holds fields required to create a Review.
type CreateReviewInput struct {
	Body      string
	Rating    int64
	ProductID uuid.UUID
}

// UpdateReviewInput holds optional fields for partial update.
type UpdateReviewInput struct {
	Body   *string `json:"body,omitempty"`
	Rating *int64  `json:"rating,omitempty"`
}
