// Code generated by axe on 2026-04-19. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/service"
)

type mockOrderRepo struct{}

func (m *mockOrderRepo) Create(_ context.Context, _ domain.CreateOrderInput) (*domain.Order, error) {
	return &domain.Order{ID: uuid.New()}, nil
}
func (m *mockOrderRepo) GetByID(_ context.Context, id uuid.UUID) (*domain.Order, error) {
	return &domain.Order{ID: id}, nil
}
func (m *mockOrderRepo) Update(_ context.Context, id uuid.UUID, _ domain.UpdateOrderInput) (*domain.Order, error) {
	return &domain.Order{ID: id}, nil
}
func (m *mockOrderRepo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockOrderRepo) List(_ context.Context, _ domain.Pagination) ([]*domain.Order, int, error) {
	return []*domain.Order{}, 0, nil
}

func TestCreateOrder_HappyPath(t *testing.T) {
	svc := service.NewOrderService(&mockOrderRepo{})
	result, err := svc.CreateOrder(context.Background(), domain.CreateOrderInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDeleteOrder_HappyPath(t *testing.T) {
	svc := service.NewOrderService(&mockOrderRepo{})
	if err := svc.DeleteOrder(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
