// Code generated by axe on 2026-04-19. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
	"github.com/axe-cute/examples-ecommerce/pkg/logger"
)

// OrderService implements domain.OrderService.
type OrderService struct {
	repo domain.OrderRepository
}

// NewOrderService creates a new OrderService.
func NewOrderService(repo domain.OrderRepository) domain.OrderService {
	return &OrderService{repo: repo}
}

func (s *OrderService) CreateOrder(ctx context.Context, input domain.CreateOrderInput) (*domain.Order, error) {
	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("OrderService.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("order created", "id", result.ID)
	return result, nil
}

func (s *OrderService) GetOrder(ctx context.Context, id uuid.UUID) (*domain.Order, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *OrderService) UpdateOrder(ctx context.Context, id uuid.UUID, input domain.UpdateOrderInput) (*domain.Order, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}
	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("OrderService.Update: %w", err)
	}
	return result, nil
}

func (s *OrderService) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *OrderService) ListOrders(ctx context.Context, p domain.Pagination) ([]*domain.Order, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}
