// Code generated by axe on 2026-04-19. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/service"
)

type mockProductRepo struct{}

func (m *mockProductRepo) Create(_ context.Context, _ domain.CreateProductInput) (*domain.Product, error) {
	return &domain.Product{ID: uuid.New()}, nil
}
func (m *mockProductRepo) GetByID(_ context.Context, id uuid.UUID) (*domain.Product, error) {
	return &domain.Product{ID: id}, nil
}
func (m *mockProductRepo) Update(_ context.Context, id uuid.UUID, _ domain.UpdateProductInput) (*domain.Product, error) {
	return &domain.Product{ID: id}, nil
}
func (m *mockProductRepo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockProductRepo) List(_ context.Context, _ domain.Pagination) ([]*domain.Product, int, error) {
	return []*domain.Product{}, 0, nil
}

func TestCreateProduct_HappyPath(t *testing.T) {
	svc := service.NewProductService(&mockProductRepo{})
	result, err := svc.CreateProduct(context.Background(), domain.CreateProductInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDeleteProduct_HappyPath(t *testing.T) {
	svc := service.NewProductService(&mockProductRepo{})
	if err := svc.DeleteProduct(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
