// Code generated by axe on 2026-04-19. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
	"github.com/axe-cute/examples-ecommerce/pkg/logger"
)

// ProductService implements domain.ProductService.
type ProductService struct {
	repo domain.ProductRepository
}

// NewProductService creates a new ProductService.
func NewProductService(repo domain.ProductRepository) domain.ProductService {
	return &ProductService{repo: repo}
}

func (s *ProductService) CreateProduct(ctx context.Context, input domain.CreateProductInput) (*domain.Product, error) {
	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("ProductService.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("product created", "id", result.ID)
	return result, nil
}

func (s *ProductService) GetProduct(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *ProductService) UpdateProduct(ctx context.Context, id uuid.UUID, input domain.UpdateProductInput) (*domain.Product, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}
	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("ProductService.Update: %w", err)
	}
	return result, nil
}

func (s *ProductService) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *ProductService) ListProducts(ctx context.Context, p domain.Pagination) ([]*domain.Product, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}
