// Code generated by axe on 2026-04-19. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
	"github.com/axe-cute/examples-ecommerce/pkg/logger"
)

// ReviewService implements domain.ReviewService.
type ReviewService struct {
	repo domain.ReviewRepository
}

// NewReviewService creates a new ReviewService.
func NewReviewService(repo domain.ReviewRepository) domain.ReviewService {
	return &ReviewService{repo: repo}
}

func (s *ReviewService) CreateReview(ctx context.Context, input domain.CreateReviewInput) (*domain.Review, error) {
	// ── Business validation ────────────────────────────────────────────────
	if input.Body == "" {
		return nil, apperror.ErrInvalidInput.WithMessage("review body is required")
	}
	if input.Rating < 1 || input.Rating > 5 {
		return nil, apperror.ErrInvalidInput.WithMessage("rating must be between 1 and 5")
	}

	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("ReviewService.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("review created", "id", result.ID, "product_id", input.ProductID, "rating", input.Rating)
	return result, nil
}

func (s *ReviewService) GetReview(ctx context.Context, id uuid.UUID) (*domain.Review, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *ReviewService) UpdateReview(ctx context.Context, id uuid.UUID, input domain.UpdateReviewInput) (*domain.Review, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}
	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("ReviewService.Update: %w", err)
	}
	return result, nil
}

func (s *ReviewService) DeleteReview(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *ReviewService) ListReviews(ctx context.Context, p domain.Pagination) ([]*domain.Review, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}
