// Code generated by axe on 2026-04-19. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/service"
)

type mockReviewRepo struct{}

func (m *mockReviewRepo) Create(_ context.Context, _ domain.CreateReviewInput) (*domain.Review, error) {
	return &domain.Review{ID: uuid.New()}, nil
}
func (m *mockReviewRepo) GetByID(_ context.Context, id uuid.UUID) (*domain.Review, error) {
	return &domain.Review{ID: id}, nil
}
func (m *mockReviewRepo) Update(_ context.Context, id uuid.UUID, _ domain.UpdateReviewInput) (*domain.Review, error) {
	return &domain.Review{ID: id}, nil
}
func (m *mockReviewRepo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockReviewRepo) List(_ context.Context, _ domain.Pagination) ([]*domain.Review, int, error) {
	return []*domain.Review{}, 0, nil
}

func TestCreateReview_HappyPath(t *testing.T) {
	svc := service.NewReviewService(&mockReviewRepo{})
	result, err := svc.CreateReview(context.Background(), domain.CreateReviewInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDeleteReview_HappyPath(t *testing.T) {
	svc := service.NewReviewService(&mockReviewRepo{})
	if err := svc.DeleteReview(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
