// Code generated by axe on 2026-04-15.
// Reference implementation: demonstrates Ent CRUD pattern for resources.
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "github.com/axe-cute/axe/ent"
	entPost "github.com/axe-cute/axe/ent/post"
	"github.com/axe-cute/axe/internal/domain"
	"github.com/axe-cute/axe/pkg/apperror"
)

// PostRepo implements domain.PostRepository using Ent.
type PostRepo struct {
	client *ent.Client
}

// NewPostRepo creates a new PostRepo.
func NewPostRepo(client *ent.Client) domain.PostRepository {
	return &PostRepo{client: client}
}

func (r *PostRepo) Create(ctx context.Context, input domain.CreatePostInput) (*domain.Post, error) {
	row, err := r.client.Post.Create().
		SetTitle(input.Title).
		SetBody(input.Body).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("PostRepo.Create: %w", err)
	}
	return postFromEnt(row), nil
}

func (r *PostRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	row, err := r.client.Post.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, apperror.ErrNotFound.WithMessage("post not found")
		}
		return nil, fmt.Errorf("PostRepo.GetByID: %w", err)
	}
	return postFromEnt(row), nil
}

func (r *PostRepo) Update(ctx context.Context, id uuid.UUID, input domain.UpdatePostInput) (*domain.Post, error) {
	builder := r.client.Post.UpdateOneID(id)
	if input.Title != nil {
		builder.SetTitle(*input.Title)
	}
	if input.Body != nil {
		builder.SetBody(*input.Body)
	}
	row, err := builder.Save(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, apperror.ErrNotFound.WithMessage("post not found")
		}
		return nil, fmt.Errorf("PostRepo.Update: %w", err)
	}
	return postFromEnt(row), nil
}

func (r *PostRepo) Delete(ctx context.Context, id uuid.UUID) error {
	err := r.client.Post.DeleteOneID(id).Exec(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return apperror.ErrNotFound.WithMessage("post not found")
		}
		return fmt.Errorf("PostRepo.Delete: %w", err)
	}
	return nil
}

func (r *PostRepo) List(ctx context.Context, p domain.Pagination) ([]*domain.Post, int, error) {
	query := r.client.Post.Query().
		Order(entPost.ByID()).
		Limit(p.Limit).
		Offset(p.Offset)

	total, err := r.client.Post.Query().Count(ctx)
	if err != nil {
		return nil, 0, fmt.Errorf("PostRepo.List count: %w", err)
	}

	rows, err := query.All(ctx)
	if err != nil {
		return nil, 0, fmt.Errorf("PostRepo.List: %w", err)
	}

	posts := make([]*domain.Post, len(rows))
	for i, row := range rows {
		posts[i] = postFromEnt(row)
	}
	return posts, total, nil
}

// postFromEnt converts an Ent Post entity to a domain Post.
func postFromEnt(row *ent.Post) *domain.Post {
	return &domain.Post{
		ID:        row.ID,
		Title:     row.Title,
		Body:      row.Body,
		CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt,
	}
}
