// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/axe-cute/examples-ecommerce/ent/predicate"
	"github.com/axe-cute/examples-ecommerce/ent/review"
	"github.com/google/uuid"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *ReviewUpdate) SetBody(v string) *ReviewUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableBody(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdate) SetRating(v int64) *ReviewUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableRating(v *int64) *ReviewUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdate) AddRating(v int64) *ReviewUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ReviewUpdate) SetProductID(v uuid.UUID) *ReviewUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableProductID(v *uuid.UUID) *ReviewUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReviewUpdate) SetUpdatedAt(v time.Time) *ReviewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdate) Mutation() *ReviewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReviewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := review.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(review.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(review.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(review.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetBody sets the "body" field.
func (_u *ReviewUpdateOne) SetBody(v string) *ReviewUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableBody(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdateOne) SetRating(v int64) *ReviewUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableRating(v *int64) *ReviewUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdateOne) AddRating(v int64) *ReviewUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ReviewUpdateOne) SetProductID(v uuid.UUID) *ReviewUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableProductID(v *uuid.UUID) *ReviewUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReviewUpdateOne) SetUpdatedAt(v time.Time) *ReviewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdateOne) Mutation() *ReviewMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Review entity.
func (_u *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReviewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := review.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(review.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(review.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(review.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Review{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
