// Code generated by axe on 2026-04-19. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/pkg/apperror"
	"github.com/axe-cute/examples-webtoon/pkg/logger"
)

// BookmarkService implements domain.BookmarkService.
type BookmarkService struct {
	repo domain.BookmarkRepository
}

// NewBookmarkService creates a new BookmarkService.
func NewBookmarkService(repo domain.BookmarkRepository) domain.BookmarkService {
	return &BookmarkService{repo: repo}
}

func (s *BookmarkService) CreateBookmark(ctx context.Context, input domain.CreateBookmarkInput) (*domain.Bookmark, error) {
	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("BookmarkService.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("bookmark created", "id", result.ID)
	return result, nil
}

func (s *BookmarkService) GetBookmark(ctx context.Context, id uuid.UUID) (*domain.Bookmark, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *BookmarkService) UpdateBookmark(ctx context.Context, id uuid.UUID, input domain.UpdateBookmarkInput) (*domain.Bookmark, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}
	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("BookmarkService.Update: %w", err)
	}
	return result, nil
}

func (s *BookmarkService) DeleteBookmark(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *BookmarkService) ListBookmarks(ctx context.Context, p domain.Pagination) ([]*domain.Bookmark, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}
