// Code generated by axe on 2026-04-19. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/pkg/apperror"
	"github.com/axe-cute/examples-webtoon/pkg/logger"
)

// SeriesService implements domain.SeriesService.
type SeriesService struct {
	repo domain.SeriesRepository
}

// NewSeriesService creates a new SeriesService.
func NewSeriesService(repo domain.SeriesRepository) domain.SeriesService {
	return &SeriesService{repo: repo}
}

func (s *SeriesService) CreateSeries(ctx context.Context, input domain.CreateSeriesInput) (*domain.Series, error) {
	// ── Business validation ────────────────────────────────────────────────
	if err := domain.ValidateCreateSeries(input); err != nil {
		return nil, apperror.ErrInvalidInput.WithMessage(err.Error())
	}

	// Default status to "ongoing" if not specified.
	if input.Status == "" {
		input.Status = domain.SeriesStatusOngoing
	}

	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("SeriesService.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("series created",
		"id", result.ID,
		"title", input.Title,
		"genre", input.Genre,
		"author", input.Author,
	)
	return result, nil
}

func (s *SeriesService) GetSeries(ctx context.Context, id uuid.UUID) (*domain.Series, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *SeriesService) UpdateSeries(ctx context.Context, id uuid.UUID, input domain.UpdateSeriesInput) (*domain.Series, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}

	// Validate status if being updated.
	if input.Status != nil && !domain.ValidSeriesStatuses[*input.Status] {
		return nil, apperror.ErrInvalidInput.WithMessage(
			fmt.Sprintf("invalid status %q — allowed: ongoing, completed, hiatus", *input.Status))
	}

	// Validate genre if being updated.
	if input.Genre != nil && *input.Genre != "" && !domain.ValidGenres[*input.Genre] {
		return nil, apperror.ErrInvalidInput.WithMessage(
			fmt.Sprintf("invalid genre %q", *input.Genre))
	}

	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("SeriesService.Update: %w", err)
	}
	return result, nil
}

func (s *SeriesService) DeleteSeries(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *SeriesService) ListSeriess(ctx context.Context, p domain.Pagination) ([]*domain.Series, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}

// ListSeriesFiltered validates the filter values and delegates to the repo.
// Genre/Status are checked against allowlists so arbitrary strings don't hit
// the DB (prevents index bloat from invalid values).
func (s *SeriesService) ListSeriesFiltered(ctx context.Context, f domain.SeriesFilter, p domain.Pagination) ([]*domain.Series, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	if f.Genre != "" && !domain.ValidGenres[f.Genre] {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(fmt.Sprintf("invalid genre %q", f.Genre))
	}
	if f.Status != "" && !domain.ValidSeriesStatuses[f.Status] {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(fmt.Sprintf("invalid status %q", f.Status))
	}
	return s.repo.ListFiltered(ctx, f, p)
}

// ListTrending returns top-N series by trending_score.
func (s *SeriesService) ListTrending(ctx context.Context, limit int) ([]*domain.Series, error) {
	return s.repo.ListTrending(ctx, limit)
}
