// Code generated by axe on 2026-04-19. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/internal/service"
)

type mockSeriesRepo struct{}

func (m *mockSeriesRepo) Create(_ context.Context, _ domain.CreateSeriesInput) (*domain.Series, error) {
	return &domain.Series{ID: uuid.New()}, nil
}
func (m *mockSeriesRepo) GetByID(_ context.Context, id uuid.UUID) (*domain.Series, error) {
	return &domain.Series{ID: id}, nil
}
func (m *mockSeriesRepo) Update(_ context.Context, id uuid.UUID, _ domain.UpdateSeriesInput) (*domain.Series, error) {
	return &domain.Series{ID: id}, nil
}
func (m *mockSeriesRepo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockSeriesRepo) List(_ context.Context, _ domain.Pagination) ([]*domain.Series, int, error) {
	return []*domain.Series{}, 0, nil
}
func (m *mockSeriesRepo) ListFiltered(_ context.Context, _ domain.SeriesFilter, _ domain.Pagination) ([]*domain.Series, int, error) {
	return []*domain.Series{}, 0, nil
}
func (m *mockSeriesRepo) ListTrending(_ context.Context, _ int) ([]*domain.Series, error) {
	return []*domain.Series{}, nil
}

func TestCreateSeries_HappyPath(t *testing.T) {
	svc := service.NewSeriesService(&mockSeriesRepo{})
	result, err := svc.CreateSeries(context.Background(), domain.CreateSeriesInput{
		Title:  "Test",
		Author: "Tester",
		Genre:  "action",
		Status: "ongoing",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDeleteSeries_HappyPath(t *testing.T) {
	svc := service.NewSeriesService(&mockSeriesRepo{})
	if err := svc.DeleteSeries(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
