// Code generated by axe on 2026-04-19. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/handler"
)

type mockOrderSvc struct{}

func (m *mockOrderSvc) CreateOrder(_ context.Context, _ domain.CreateOrderInput) (*domain.Order, error) {
	return &domain.Order{ID: uuid.New()}, nil
}
func (m *mockOrderSvc) GetOrder(_ context.Context, id uuid.UUID) (*domain.Order, error) {
	return &domain.Order{ID: id}, nil
}
func (m *mockOrderSvc) UpdateOrder(_ context.Context, id uuid.UUID, _ domain.UpdateOrderInput) (*domain.Order, error) {
	return &domain.Order{ID: id}, nil
}
func (m *mockOrderSvc) DeleteOrder(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockOrderSvc) ListOrders(_ context.Context, _ domain.Pagination) ([]*domain.Order, int, error) {
	return []*domain.Order{}, 0, nil
}

// setupOrderRouter mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setupOrderRouter() *chi.Mux {
	h := handler.NewOrderHandler(&mockOrderSvc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/orders/{id}", h.GetOrder)
	r.Put("/api/v1/orders/{id}", h.UpdateOrder)
	r.Delete("/api/v1/orders/{id}", h.DeleteOrder)
	r.Get("/api/v1/orders", h.ListOrders)
	r.Post("/api/v1/orders", h.CreateOrder)
	return r
}

func TestOrder_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/orders/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupOrderRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestOrder_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/orders/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupOrderRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestOrder_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/orders", nil)
	rec := httptest.NewRecorder()
	setupOrderRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
