// Code generated by axe on 2026-04-19. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/handler/middleware"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
	"github.com/axe-cute/examples-ecommerce/pkg/jwtauth"
)

// OrderHandler handles HTTP requests for the Order domain.
type OrderHandler struct {
	svc       domain.OrderService
	jwtSvc    *jwtauth.Service // required: set via WithJWTAuth option
	blocklist middleware.Blocklist
}

// NewOrderHandler creates a new OrderHandler.
func NewOrderHandler(svc domain.OrderService) *OrderHandler {
	return &OrderHandler{svc: svc}
}

// WithJWTAuth sets the JWT service and optional blocklist for route protection.
// Call before registering routes:
//
//	h := handler.NewOrderHandler(svc).WithJWTAuth(jwtSvc, cacheClient)
func (h *OrderHandler) WithJWTAuth(svc *jwtauth.Service, bl middleware.Blocklist) *OrderHandler {
	h.jwtSvc = svc
	h.blocklist = bl
	return h
}

// Routes returns a Chi router with all order endpoints.
// Register in main.go: r.Mount("/api/v1/orders", orderHandler.Routes())
func (h *OrderHandler) Routes() chi.Router {
	r := chi.NewRouter()
	// Authentication required for all order routes
	r.Use(middleware.JWTAuth(h.jwtSvc, h.blocklist))

	// Standard CRUD
	r.Post("/", h.CreateOrder)
	r.Get("/", h.ListOrders)
	r.Get("/{id}", h.GetOrder)
	r.Put("/{id}", h.UpdateOrder)
	r.Delete("/{id}", h.DeleteOrder)

	// Business flows
	r.Post("/place", h.PlaceOrder)        // the hero endpoint
	r.Put("/{id}/status", h.UpdateStatus) // status machine

	return r
}

// createOrderRequest is the POST request body.
type createOrderRequest struct {
	Total  float64 `json:"total"`
	Status string  `json:"status"`
}

// orderResponse is the API response shape.
type orderResponse struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id,omitempty"`
	Total     float64            `json:"total"`
	Status    string             `json:"status"`
	Items     []domain.OrderItem `json:"items,omitempty"`
	CreatedAt string             `json:"created_at"`
	UpdatedAt string             `json:"updated_at"`
}

func toOrderResponse(e *domain.Order) *orderResponse {
	return &orderResponse{
		ID:        e.ID.String(),
		UserID:    e.UserID,
		Total:     e.Total,
		Status:    e.Status,
		Items:     e.Items,
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *OrderHandler) CreateOrder(w http.ResponseWriter, r *http.Request) {
	var req createOrderRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.CreateOrder(r.Context(), domain.CreateOrderInput{
		Total:  req.Total,
		Status: req.Status,
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toOrderResponse(result))
}

func (h *OrderHandler) GetOrder(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.GetOrder(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toOrderResponse(result))
}

func (h *OrderHandler) UpdateOrder(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.UpdateOrderInput
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.UpdateOrder(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toOrderResponse(result))
}

func (h *OrderHandler) DeleteOrder(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.DeleteOrder(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *OrderHandler) ListOrders(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.ListOrders(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*orderResponse, len(results))
	for i, e := range results {
		data[i] = toOrderResponse(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}

// ── PlaceOrder — the hero endpoint ───────────────────────────────────────────

type placeOrderRequest struct {
	Items []domain.PlaceOrderItemInput `json:"items"`
}

// PlaceOrder handles POST /orders/place.
// Validates stock, calculates total, creates order + items, deducts inventory.
func (h *OrderHandler) PlaceOrder(w http.ResponseWriter, r *http.Request) {
	var req placeOrderRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}

	// Extract user ID from JWT claims (set by auth middleware).
	userID := "anonymous" // fallback
	if claims := middleware.ClaimsFromCtx(r.Context()); claims != nil {
		userID = claims.Subject
	}

	order, err := h.svc.PlaceOrder(r.Context(), userID, req.Items)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toOrderResponse(order))
}

// ── UpdateStatus — status machine endpoint ───────────────────────────────────

type updateStatusRequest struct {
	Status string `json:"status"`
}

// UpdateStatus handles PUT /orders/{id}/status.
// Validates state transitions: pending→confirmed→shipped→delivered.
func (h *OrderHandler) UpdateStatus(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req updateStatusRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	order, err := h.svc.UpdateStatus(r.Context(), id, req.Status)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toOrderResponse(order))
}
