// Code generated by axe on 2026-04-19. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/handler"
)

type mockProductSvc struct{}

func (m *mockProductSvc) CreateProduct(_ context.Context, _ domain.CreateProductInput) (*domain.Product, error) {
	return &domain.Product{ID: uuid.New()}, nil
}
func (m *mockProductSvc) GetProduct(_ context.Context, id uuid.UUID) (*domain.Product, error) {
	return &domain.Product{ID: id}, nil
}
func (m *mockProductSvc) UpdateProduct(_ context.Context, id uuid.UUID, _ domain.UpdateProductInput) (*domain.Product, error) {
	return &domain.Product{ID: id}, nil
}
func (m *mockProductSvc) DeleteProduct(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockProductSvc) ListProducts(_ context.Context, _ domain.Pagination) ([]*domain.Product, int, error) {
	return []*domain.Product{}, 0, nil
}

// setupProductRouter mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setupProductRouter() *chi.Mux {
	h := handler.NewProductHandler(&mockProductSvc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/products/{id}", h.GetProduct)
	r.Put("/api/v1/products/{id}", h.UpdateProduct)
	r.Delete("/api/v1/products/{id}", h.DeleteProduct)
	r.Get("/api/v1/products", h.ListProducts)
	r.Post("/api/v1/products", h.CreateProduct)
	return r
}

func TestProduct_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/products/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupProductRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestProduct_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/products/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupProductRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestProduct_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/products", nil)
	rec := httptest.NewRecorder()
	setupProductRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
