// Code generated by axe on 2026-04-19. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/handler/middleware"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
	"github.com/axe-cute/examples-ecommerce/pkg/jwtauth"
)

// ProductHandler handles HTTP requests for the Product domain.
type ProductHandler struct {
	svc domain.ProductService
	jwtSvc   *jwtauth.Service   // required: set via WithJWTAuth option
	blocklist middleware.Blocklist
}

// NewProductHandler creates a new ProductHandler.
func NewProductHandler(svc domain.ProductService) *ProductHandler {
	return &ProductHandler{svc: svc}
}

// WithJWTAuth sets the JWT service and optional blocklist for route protection.
// Call before registering routes:
//
//	h := handler.NewProductHandler(svc).WithJWTAuth(jwtSvc, cacheClient)
func (h *ProductHandler) WithJWTAuth(svc *jwtauth.Service, bl middleware.Blocklist) *ProductHandler {
	h.jwtSvc = svc
	h.blocklist = bl
	return h
}


// Routes returns a Chi router with all product endpoints.
// Register in main.go: r.Mount("/api/v1/products", productHandler.Routes())
func (h *ProductHandler) Routes() chi.Router {
	r := chi.NewRouter()
	// Authentication required for all product routes
	r.Use(middleware.JWTAuth(h.jwtSvc, h.blocklist))
	r.Post("/", h.CreateProduct)
	r.Get("/", h.ListProducts)
	r.Get("/{id}", h.GetProduct)
	r.Put("/{id}", h.UpdateProduct)
	r.Delete("/{id}", h.DeleteProduct)
	return r
}

// createProductRequest is the POST request body.
type createProductRequest struct {
	Name string `json:"name"`
	Description string `json:"description"`
	Price float64 `json:"price"`
	Stock int64 `json:"stock"`
	ImageUrl string `json:"image_url"`
}

// productResponse is the API response shape.
type productResponse struct {
	ID        string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	Price float64 `json:"price"`
	Stock int64 `json:"stock"`
	ImageUrl string `json:"image_url"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func toProductResponse(e *domain.Product) *productResponse {
	return &productResponse{
		ID: e.ID.String(),
		Name: e.Name,
		Description: e.Description,
		Price: e.Price,
		Stock: e.Stock,
		ImageUrl: e.ImageUrl,
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *ProductHandler) CreateProduct(w http.ResponseWriter, r *http.Request) {
	var req createProductRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.CreateProduct(r.Context(), domain.CreateProductInput{
		Name: req.Name,
		Description: req.Description,
		Price: req.Price,
		Stock: req.Stock,
		ImageUrl: req.ImageUrl,
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toProductResponse(result))
}

func (h *ProductHandler) GetProduct(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.GetProduct(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toProductResponse(result))
}

func (h *ProductHandler) UpdateProduct(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.UpdateProductInput
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.UpdateProduct(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toProductResponse(result))
}

func (h *ProductHandler) DeleteProduct(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.DeleteProduct(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *ProductHandler) ListProducts(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.ListProducts(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*productResponse, len(results))
	for i, e := range results {
		data[i] = toProductResponse(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
