// Code generated by axe on 2026-04-19. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/handler"
)

type mockReviewSvc struct{}

func (m *mockReviewSvc) CreateReview(_ context.Context, _ domain.CreateReviewInput) (*domain.Review, error) {
	return &domain.Review{ID: uuid.New()}, nil
}
func (m *mockReviewSvc) GetReview(_ context.Context, id uuid.UUID) (*domain.Review, error) {
	return &domain.Review{ID: id}, nil
}
func (m *mockReviewSvc) UpdateReview(_ context.Context, id uuid.UUID, _ domain.UpdateReviewInput) (*domain.Review, error) {
	return &domain.Review{ID: id}, nil
}
func (m *mockReviewSvc) DeleteReview(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockReviewSvc) ListReviews(_ context.Context, _ domain.Pagination) ([]*domain.Review, int, error) {
	return []*domain.Review{}, 0, nil
}

// setupReviewRouter mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setupReviewRouter() *chi.Mux {
	h := handler.NewReviewHandler(&mockReviewSvc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/reviews/{id}", h.GetReview)
	r.Put("/api/v1/reviews/{id}", h.UpdateReview)
	r.Delete("/api/v1/reviews/{id}", h.DeleteReview)
	r.Get("/api/v1/reviews", h.ListReviews)
	r.Post("/api/v1/reviews", h.CreateReview)
	return r
}

func TestReview_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/reviews/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupReviewRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func TestReview_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/reviews/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setupReviewRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func TestReview_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/reviews", nil)
	rec := httptest.NewRecorder()
	setupReviewRouter().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
