// Code generated by axe on 2026-04-19. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/internal/handler/middleware"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
	"github.com/axe-cute/examples-ecommerce/pkg/jwtauth"
)

// ReviewHandler handles HTTP requests for the Review domain.
type ReviewHandler struct {
	svc domain.ReviewService
	jwtSvc   *jwtauth.Service   // required: set via WithJWTAuth option
	blocklist middleware.Blocklist
}

// NewReviewHandler creates a new ReviewHandler.
func NewReviewHandler(svc domain.ReviewService) *ReviewHandler {
	return &ReviewHandler{svc: svc}
}

// WithJWTAuth sets the JWT service and optional blocklist for route protection.
// Call before registering routes:
//
//	h := handler.NewReviewHandler(svc).WithJWTAuth(jwtSvc, cacheClient)
func (h *ReviewHandler) WithJWTAuth(svc *jwtauth.Service, bl middleware.Blocklist) *ReviewHandler {
	h.jwtSvc = svc
	h.blocklist = bl
	return h
}


// Routes returns a Chi router with all review endpoints.
// Register in main.go: r.Mount("/api/v1/reviews", reviewHandler.Routes())
func (h *ReviewHandler) Routes() chi.Router {
	r := chi.NewRouter()
	// Authentication required for all review routes
	r.Use(middleware.JWTAuth(h.jwtSvc, h.blocklist))
	r.Post("/", h.CreateReview)
	r.Get("/", h.ListReviews)
	r.Get("/{id}", h.GetReview)
	r.Put("/{id}", h.UpdateReview)
	r.Delete("/{id}", h.DeleteReview)
	return r
}

// createReviewRequest is the POST request body.
type createReviewRequest struct {
	Body string `json:"body"`
	Rating int64 `json:"rating"`
}

// reviewResponse is the API response shape.
type reviewResponse struct {
	ID        string `json:"id"`
	Body string `json:"body"`
	Rating int64 `json:"rating"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func toReviewResponse(e *domain.Review) *reviewResponse {
	return &reviewResponse{
		ID: e.ID.String(),
		Body: e.Body,
		Rating: e.Rating,
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *ReviewHandler) CreateReview(w http.ResponseWriter, r *http.Request) {
	var req createReviewRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.CreateReview(r.Context(), domain.CreateReviewInput{
		Body: req.Body,
		Rating: req.Rating,
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, toReviewResponse(result))
}

func (h *ReviewHandler) GetReview(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.GetReview(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toReviewResponse(result))
}

func (h *ReviewHandler) UpdateReview(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.UpdateReviewInput
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.UpdateReview(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, toReviewResponse(result))
}

func (h *ReviewHandler) DeleteReview(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.DeleteReview(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *ReviewHandler) ListReviews(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.ListReviews(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*reviewResponse, len(results))
	for i, e := range results {
		data[i] = toReviewResponse(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
