// Code generated by axe on 2026-04-15.
// After editing: go generate ./ent/...
package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// Post holds the schema definition for the Post entity.
type Post struct {
	ent.Schema
}

// Fields defines Post entity fields.
func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable(),
		field.String("title"),
		field.String("body"),
		field.Bool("published"),
		field.Int64("views"),
		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}
}

// Edges defines Post entity relationships.
func (Post) Edges() []ent.Edge {
	return nil
}
