// Code generated by axe on 2026-04-19.
// IMPLEMENT: complete after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "github.com/axe-cute/examples-webtoon/ent"
	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/pkg/apperror"
)

// EpisodeRepo implements domain.EpisodeRepository using Ent.
type EpisodeRepo struct {
	client *ent.Client
}

// NewEpisodeRepo creates a new EpisodeRepo.
func NewEpisodeRepo(client *ent.Client) domain.EpisodeRepository {
	return &EpisodeRepo{client: client}
}

func (r *EpisodeRepo) Create(ctx context.Context, input domain.CreateEpisodeInput) (*domain.Episode, error) {
	// IMPLEMENT: r.client.Episode.Create().Set...Save(ctx)
	return nil, fmt.Errorf("EpisodeRepo.Create: not implemented — run go generate ./ent/... first")
}

func (r *EpisodeRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Episode, error) {
	// IMPLEMENT: r.client.Episode.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("episode not found")
}

func (r *EpisodeRepo) Update(ctx context.Context, id uuid.UUID, _ domain.UpdateEpisodeInput) (*domain.Episode, error) {
	// IMPLEMENT: r.client.Episode.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("EpisodeRepo.Update: not implemented")
}

func (r *EpisodeRepo) Delete(ctx context.Context, id uuid.UUID) error {
	// IMPLEMENT: soft-delete or hard-delete
	return fmt.Errorf("EpisodeRepo.Delete: not implemented")
}

func (r *EpisodeRepo) List(ctx context.Context, p domain.Pagination) ([]*domain.Episode, int, error) {
	// IMPLEMENT: paginated query
	return []*domain.Episode{}, 0, nil
}
