// Code generated by axe on 2026-04-19.
// IMPLEMENT: complete after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "github.com/axe-cute/examples-webtoon/ent"
	"github.com/axe-cute/examples-webtoon/internal/domain"
	"github.com/axe-cute/examples-webtoon/pkg/apperror"
)

// SeriesRepo implements domain.SeriesRepository using Ent.
type SeriesRepo struct {
	client *ent.Client
}

// NewSeriesRepo creates a new SeriesRepo.
func NewSeriesRepo(client *ent.Client) domain.SeriesRepository {
	return &SeriesRepo{client: client}
}

func (r *SeriesRepo) Create(ctx context.Context, input domain.CreateSeriesInput) (*domain.Series, error) {
	// IMPLEMENT: r.client.Series.Create().Set...Save(ctx)
	return nil, fmt.Errorf("SeriesRepo.Create: not implemented — run go generate ./ent/... first")
}

func (r *SeriesRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Series, error) {
	// IMPLEMENT: r.client.Series.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("series not found")
}

func (r *SeriesRepo) Update(ctx context.Context, id uuid.UUID, _ domain.UpdateSeriesInput) (*domain.Series, error) {
	// IMPLEMENT: r.client.Series.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("SeriesRepo.Update: not implemented")
}

func (r *SeriesRepo) Delete(ctx context.Context, id uuid.UUID) error {
	// IMPLEMENT: soft-delete or hard-delete
	return fmt.Errorf("SeriesRepo.Delete: not implemented")
}

func (r *SeriesRepo) List(ctx context.Context, p domain.Pagination) ([]*domain.Series, int, error) {
	// IMPLEMENT: paginated query
	return []*domain.Series{}, 0, nil
}
