// Code generated by axe on 2026-04-19.
// IMPLEMENT: complete after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "github.com/axe-cute/examples-ecommerce/ent"
	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
)

// OrderRepo implements domain.OrderRepository using Ent.
type OrderRepo struct {
	client *ent.Client
}

// NewOrderRepo creates a new OrderRepo.
func NewOrderRepo(client *ent.Client) domain.OrderRepository {
	return &OrderRepo{client: client}
}

func (r *OrderRepo) Create(ctx context.Context, input domain.CreateOrderInput) (*domain.Order, error) {
	// IMPLEMENT: r.client.Order.Create().Set...Save(ctx)
	return nil, fmt.Errorf("OrderRepo.Create: not implemented — run go generate ./ent/... first")
}

func (r *OrderRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Order, error) {
	// IMPLEMENT: r.client.Order.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("order not found")
}

func (r *OrderRepo) Update(ctx context.Context, id uuid.UUID, _ domain.UpdateOrderInput) (*domain.Order, error) {
	// IMPLEMENT: r.client.Order.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("OrderRepo.Update: not implemented")
}

func (r *OrderRepo) Delete(ctx context.Context, id uuid.UUID) error {
	// IMPLEMENT: soft-delete or hard-delete
	return fmt.Errorf("OrderRepo.Delete: not implemented")
}

func (r *OrderRepo) List(ctx context.Context, p domain.Pagination) ([]*domain.Order, int, error) {
	// IMPLEMENT: paginated query
	return []*domain.Order{}, 0, nil
}
