// Code generated by axe on 2026-04-19.
// IMPLEMENT: complete after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "github.com/axe-cute/examples-ecommerce/ent"
	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
)

// ProductRepo implements domain.ProductRepository using Ent.
type ProductRepo struct {
	client *ent.Client
}

// NewProductRepo creates a new ProductRepo.
func NewProductRepo(client *ent.Client) domain.ProductRepository {
	return &ProductRepo{client: client}
}

func (r *ProductRepo) Create(ctx context.Context, input domain.CreateProductInput) (*domain.Product, error) {
	// IMPLEMENT: r.client.Product.Create().Set...Save(ctx)
	return nil, fmt.Errorf("ProductRepo.Create: not implemented — run go generate ./ent/... first")
}

func (r *ProductRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	// IMPLEMENT: r.client.Product.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("product not found")
}

func (r *ProductRepo) Update(ctx context.Context, id uuid.UUID, _ domain.UpdateProductInput) (*domain.Product, error) {
	// IMPLEMENT: r.client.Product.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("ProductRepo.Update: not implemented")
}

func (r *ProductRepo) Delete(ctx context.Context, id uuid.UUID) error {
	// IMPLEMENT: soft-delete or hard-delete
	return fmt.Errorf("ProductRepo.Delete: not implemented")
}

func (r *ProductRepo) List(ctx context.Context, p domain.Pagination) ([]*domain.Product, int, error) {
	// IMPLEMENT: paginated query
	return []*domain.Product{}, 0, nil
}
