// Code generated by axe on 2026-04-19.
// IMPLEMENT: complete after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "github.com/axe-cute/examples-ecommerce/ent"
	"github.com/axe-cute/examples-ecommerce/internal/domain"
	"github.com/axe-cute/examples-ecommerce/pkg/apperror"
)

// ReviewRepo implements domain.ReviewRepository using Ent.
type ReviewRepo struct {
	client *ent.Client
}

// NewReviewRepo creates a new ReviewRepo.
func NewReviewRepo(client *ent.Client) domain.ReviewRepository {
	return &ReviewRepo{client: client}
}

func (r *ReviewRepo) Create(ctx context.Context, input domain.CreateReviewInput) (*domain.Review, error) {
	// IMPLEMENT: r.client.Review.Create().Set...Save(ctx)
	return nil, fmt.Errorf("ReviewRepo.Create: not implemented — run go generate ./ent/... first")
}

func (r *ReviewRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Review, error) {
	// IMPLEMENT: r.client.Review.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("review not found")
}

func (r *ReviewRepo) Update(ctx context.Context, id uuid.UUID, _ domain.UpdateReviewInput) (*domain.Review, error) {
	// IMPLEMENT: r.client.Review.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("ReviewRepo.Update: not implemented")
}

func (r *ReviewRepo) Delete(ctx context.Context, id uuid.UUID) error {
	// IMPLEMENT: soft-delete or hard-delete
	return fmt.Errorf("ReviewRepo.Delete: not implemented")
}

func (r *ReviewRepo) List(ctx context.Context, p domain.Pagination) ([]*domain.Review, int, error) {
	// IMPLEMENT: paginated query
	return []*domain.Review{}, 0, nil
}
