package generate

// bt returns a backtick character — used in templates where raw string literals
// cannot contain a literal backtick.
func bt() string { return "`" }

// ── Domain template ───────────────────────────────────────────────────────────

var domainTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// {{.Name}} is the {{.Name}} domain entity.
type {{.Name}} struct {
	ID {{range .Fields}}{{end}}uuid.UUID
{{- range .Fields}}
	{{title .Name}} {{.Type}}
{{- end}}
{{- if .BelongsTo}}
	{{.BelongsTo}}ID uuid.UUID
{{- end}}
	CreatedAt time.Time
	UpdatedAt time.Time
}

// {{.Name}}Repository defines data access for {{.Name}}.
// Implemented in internal/repository/{{.NameSnake}}_repo.go.
type {{.Name}}Repository interface {
	Create(ctx context.Context, input Create{{.Name}}Input) (*{{.Name}}, error)
	Update(ctx context.Context, id uuid.UUID, input Update{{.Name}}Input) (*{{.Name}}, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
	List(ctx context.Context, pagination Pagination) ([]*{{.Name}}, int, error)
}

// {{.Name}}Service defines business operations for {{.Name}}.
// Implemented in internal/service/{{.NameSnake}}_service.go.
type {{.Name}}Service interface {
	Create{{.Name}}(ctx context.Context, input Create{{.Name}}Input) (*{{.Name}}, error)
	Get{{.Name}}(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
	Update{{.Name}}(ctx context.Context, id uuid.UUID, input Update{{.Name}}Input) (*{{.Name}}, error)
	Delete{{.Name}}(ctx context.Context, id uuid.UUID) error
	List{{.Name}}s(ctx context.Context, pagination Pagination) ([]*{{.Name}}, int, error)
}

// Create{{.Name}}Input holds fields required to create a {{.Name}}.
type Create{{.Name}}Input struct {
{{- range .Fields}}
	{{title .Name}} {{.Type}}
{{- end}}
{{- if .BelongsTo}}
	{{.BelongsTo}}ID uuid.UUID
{{- end}}
}

// Update{{.Name}}Input holds optional fields for partial update.
type Update{{.Name}}Input struct {
{{- range .Fields}}
	{{title .Name}} *{{.Type}}
{{- end}}
}
`

// ── Handler template ──────────────────────────────────────────────────────────

var handlerTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/internal/handler/middleware"
	"{{.Module}}/pkg/apperror"
)

// {{.Name}}Handler handles HTTP requests for the {{.Name}} domain.
type {{.Name}}Handler struct {
	svc domain.{{.Name}}Service
}

// New{{.Name}}Handler creates a new {{.Name}}Handler.
func New{{.Name}}Handler(svc domain.{{.Name}}Service) *{{.Name}}Handler {
	return &{{.Name}}Handler{svc: svc}
}

// Routes returns a Chi router with all {{.NameLower}} endpoints.
// Register in main.go: r.Mount("/api/v1/{{.NamePlural}}", {{.NameLower}}Handler.Routes())
func (h *{{.Name}}Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Post("/", h.Create{{.Name}})
	r.Get("/", h.List{{.Name}}s)
	r.Get("/{id}", h.Get{{.Name}})
	r.Put("/{id}", h.Update{{.Name}})
	r.Delete("/{id}", h.Delete{{.Name}})
	return r
}

// create{{.Name}}Request is the POST request body.
// TODO: add json struct tags after generation.
type create{{.Name}}Request struct {
{{- range .Fields}}
	{{title .Name}} {{.Type}}
{{- end}}
}

// {{.NameLower}}Response is the API response shape.
// TODO: add json struct tags after generation.
type {{.NameLower}}Response struct {
	ID        string
{{- range .Fields}}
	{{title .Name}} {{.Type}}
{{- end}}
	CreatedAt string
	UpdatedAt string
}

func to{{.Name}}Response(e *domain.{{.Name}}) *{{.NameLower}}Response {
	return &{{.NameLower}}Response{
		ID: e.ID.String(),
{{- range .Fields}}
		{{title .Name}}: e.{{title .Name}},
{{- end}}
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *{{.Name}}Handler) Create{{.Name}}(w http.ResponseWriter, r *http.Request) {
	var req create{{.Name}}Request
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.Create{{.Name}}(r.Context(), domain.Create{{.Name}}Input{
{{- range .Fields}}
		{{title .Name}}: req.{{title .Name}},
{{- end}}
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, to{{.Name}}Response(result))
}

func (h *{{.Name}}Handler) Get{{.Name}}(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.Get{{.Name}}(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, to{{.Name}}Response(result))
}

func (h *{{.Name}}Handler) Update{{.Name}}(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.Update{{.Name}}Input
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.Update{{.Name}}(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, to{{.Name}}Response(result))
}

func (h *{{.Name}}Handler) Delete{{.Name}}(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.Delete{{.Name}}(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *{{.Name}}Handler) List{{.Name}}s(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.List{{.Name}}s(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*{{.NameLower}}Response, len(results))
	for i, e := range results {
		data[i] = to{{.Name}}Response(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
`

// ── Handler test template ─────────────────────────────────────────────────────

var handlerTestTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/internal/handler"
)

type mock{{.Name}}Svc struct{}

func (m *mock{{.Name}}Svc) Create{{.Name}}(_ context.Context, _ domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: uuid.New()}, nil
}
func (m *mock{{.Name}}Svc) Get{{.Name}}(_ context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Svc) Update{{.Name}}(_ context.Context, id uuid.UUID, _ domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Svc) Delete{{.Name}}(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mock{{.Name}}Svc) List{{.Name}}s(_ context.Context, _ domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	return []*domain.{{.Name}}{}, 0, nil
}

func setup{{.Name}}Router() *chi.Mux {
	h := handler.New{{.Name}}Handler(&mock{{.Name}}Svc{})
	r := chi.NewRouter()
	r.Mount("/api/v1/{{.NamePlural}}", h.Routes())
	return r
}

func Test{{.Name}}_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/{{.NamePlural}}/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setup{{.Name}}Router().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func Test{{.Name}}_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/{{.NamePlural}}/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setup{{.Name}}Router().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func Test{{.Name}}_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/{{.NamePlural}}", nil)
	rec := httptest.NewRecorder()
	setup{{.Name}}Router().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
`

// ── Service template ──────────────────────────────────────────────────────────

var serviceTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/pkg/apperror"
	"{{.Module}}/pkg/logger"
)

// {{.Name}}Service implements domain.{{.Name}}Service.
type {{.Name}}Service struct {
	repo domain.{{.Name}}Repository
}

// New{{.Name}}Service creates a new {{.Name}}Service.
func New{{.Name}}Service(repo domain.{{.Name}}Repository) domain.{{.Name}}Service {
	return &{{.Name}}Service{repo: repo}
}

func (s *{{.Name}}Service) Create{{.Name}}(ctx context.Context, input domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("{{.Name}}Service.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("{{.NameLower}} created", "id", result.ID)
	return result, nil
}

func (s *{{.Name}}Service) Get{{.Name}}(ctx context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *{{.Name}}Service) Update{{.Name}}(ctx context.Context, id uuid.UUID, input domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}
	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("{{.Name}}Service.Update: %w", err)
	}
	return result, nil
}

func (s *{{.Name}}Service) Delete{{.Name}}(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *{{.Name}}Service) List{{.Name}}s(ctx context.Context, p domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}
`

// ── Service test template ─────────────────────────────────────────────────────

var serviceTestTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/internal/service"
)

type mock{{.Name}}Repo struct{}

func (m *mock{{.Name}}Repo) Create(_ context.Context, _ domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: uuid.New()}, nil
}
func (m *mock{{.Name}}Repo) GetByID(_ context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Repo) Update(_ context.Context, id uuid.UUID, _ domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Repo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mock{{.Name}}Repo) List(_ context.Context, _ domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	return []*domain.{{.Name}}{}, 0, nil
}

func TestCreate{{.Name}}_HappyPath(t *testing.T) {
	svc := service.New{{.Name}}Service(&mock{{.Name}}Repo{})
	result, err := svc.Create{{.Name}}(context.Background(), domain.Create{{.Name}}Input{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDelete{{.Name}}_HappyPath(t *testing.T) {
	svc := service.New{{.Name}}Service(&mock{{.Name}}Repo{})
	if err := svc.Delete{{.Name}}(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
`

// ── Repository template ───────────────────────────────────────────────────────

var repoTmpl = `// Code generated by axe on {{.Date}}.
// TODO: implement after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "{{.Module}}/ent"
	"{{.Module}}/internal/domain"
	"{{.Module}}/pkg/apperror"
)

// {{.Name}}Repo implements domain.{{.Name}}Repository using Ent.
type {{.Name}}Repo struct {
	client *ent.Client
}

// New{{.Name}}Repo creates a new {{.Name}}Repo.
func New{{.Name}}Repo(client *ent.Client) domain.{{.Name}}Repository {
	return &{{.Name}}Repo{client: client}
}

func (r *{{.Name}}Repo) Create(ctx context.Context, input domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	// TODO: r.client.{{.Name}}.Create().Set...Save(ctx)
	return nil, fmt.Errorf("{{.Name}}Repo.Create: not implemented — run go generate ./ent/... first")
}

func (r *{{.Name}}Repo) GetByID(ctx context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	// TODO: r.client.{{.Name}}.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("{{.NameLower}} not found")
}

func (r *{{.Name}}Repo) Update(ctx context.Context, id uuid.UUID, _ domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	// TODO: r.client.{{.Name}}.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("{{.Name}}Repo.Update: not implemented")
}

func (r *{{.Name}}Repo) Delete(ctx context.Context, id uuid.UUID) error {
	// TODO: soft-delete or hard-delete
	return fmt.Errorf("{{.Name}}Repo.Delete: not implemented")
}

func (r *{{.Name}}Repo) List(ctx context.Context, p domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	// TODO: paginated query
	return []*domain.{{.Name}}{}, 0, nil
}
`

// ── Ent schema template ───────────────────────────────────────────────────────

var entSchemaTmpl = `// Code generated by axe on {{.Date}}.
// After editing: go generate ./ent/...
package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// {{.Name}} holds the schema definition for the {{.Name}} entity.
type {{.Name}} struct {
	ent.Schema
}

// Fields defines {{.Name}} entity fields.
func ({{.Name}}) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable(),
{{- range .Fields}}
		{{.EntType}}("{{.NameSnake}}"),
{{- end}}
{{- if .BelongsTo}}
		field.UUID("{{snake .BelongsTo}}_id", uuid.UUID{}),
{{- end}}
		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}
}

// Edges defines {{.Name}} entity relationships.
func ({{.Name}}) Edges() []ent.Edge {
	return nil
}
`

// ── SQL query template ────────────────────────────────────────────────────────

var sqlQueryTmpl = `-- {{.Name}} queries for sqlc — Generated: {{.Date}}

-- name: Get{{.Name}}ByID :one
SELECT id,{{range .Fields}} {{.NameSnake}},{{end}} created_at, updated_at
FROM {{.NamePlural}}
WHERE id = $1
LIMIT 1;

-- name: List{{.Name}}s :many
SELECT id,{{range .Fields}} {{.NameSnake}},{{end}} created_at, updated_at
FROM {{.NamePlural}}
ORDER BY created_at DESC
LIMIT $1 OFFSET $2;

-- name: Count{{.Name}}s :one
SELECT COUNT(*) FROM {{.NamePlural}};
`

// ── Migration template ────────────────────────────────────────────────────────

var migrationTmpl = `-- Migration: Create {{.NamePlural}} table — Generated: {{.Date}}

CREATE TABLE IF NOT EXISTS {{.NamePlural}} (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
{{- range .Fields}}
    {{.NameSnake}}    {{.SQLType}}    NOT NULL,
{{- end}}
{{- if .BelongsTo}}
    {{snake .BelongsTo}}_id UUID NOT NULL REFERENCES {{snake .BelongsTo}}s(id),
{{- end}}
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_{{.NamePlural}}_created ON {{.NamePlural}}(created_at DESC);

CREATE OR REPLACE TRIGGER set_{{.NamePlural}}_updated_at
    BEFORE UPDATE ON {{.NamePlural}}
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();
`
