package generate

// bt returns a backtick character — used in templates where raw string literals
// cannot contain a literal backtick.
func bt() string { return "`" }

// ── Domain template ───────────────────────────────────────────────────────────

var domainTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// {{.Name}} is the {{.Name}} domain entity.
type {{.Name}} struct {
	ID {{range .Fields}}{{end}}uuid.UUID
{{- range .Fields}}
	{{title .Name}} {{.Type}}
{{- end}}
{{- if .BelongsTo}}
	{{.BelongsTo}}ID uuid.UUID
{{- end}}
	CreatedAt time.Time
	UpdatedAt time.Time
}

// {{.Name}}Repository defines data access for {{.Name}}.
// Implemented in internal/repository/{{.NameSnake}}_repo.go.
type {{.Name}}Repository interface {
	Create(ctx context.Context, input Create{{.Name}}Input) (*{{.Name}}, error)
	Update(ctx context.Context, id uuid.UUID, input Update{{.Name}}Input) (*{{.Name}}, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
	List(ctx context.Context, pagination Pagination) ([]*{{.Name}}, int, error)
}

// {{.Name}}Service defines business operations for {{.Name}}.
// Implemented in internal/service/{{.NameSnake}}_service.go.
type {{.Name}}Service interface {
	Create{{.Name}}(ctx context.Context, input Create{{.Name}}Input) (*{{.Name}}, error)
	Get{{.Name}}(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
	Update{{.Name}}(ctx context.Context, id uuid.UUID, input Update{{.Name}}Input) (*{{.Name}}, error)
	Delete{{.Name}}(ctx context.Context, id uuid.UUID) error
	List{{.Name}}s(ctx context.Context, pagination Pagination) ([]*{{.Name}}, int, error)
}

// Create{{.Name}}Input holds fields required to create a {{.Name}}.
type Create{{.Name}}Input struct {
{{- range .Fields}}
	{{title .Name}} {{.Type}}
{{- end}}
{{- if .BelongsTo}}
	{{.BelongsTo}}ID uuid.UUID
{{- end}}
}

// Update{{.Name}}Input holds optional fields for partial update.
type Update{{.Name}}Input struct {
{{- range .Fields}}
	{{title .Name}} *{{.Type}} {{bt}}json:"{{.NameSnake}},omitempty"{{bt}}
{{- end}}
}
`

// ── Handler template ──────────────────────────────────────────────────────────

var handlerTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/internal/handler/middleware"
	"{{.Module}}/pkg/apperror"
{{- if .WithAuth}}
	"{{.Module}}/pkg/jwtauth"
{{- end}}
)

// {{.Name}}Handler handles HTTP requests for the {{.Name}} domain.
type {{.Name}}Handler struct {
	svc domain.{{.Name}}Service
{{- if .WithAuth}}
	jwtSvc   *jwtauth.Service   // required: set via WithJWTAuth option
	blocklist middleware.Blocklist
{{- end}}
}

// New{{.Name}}Handler creates a new {{.Name}}Handler.
func New{{.Name}}Handler(svc domain.{{.Name}}Service) *{{.Name}}Handler {
	return &{{.Name}}Handler{svc: svc}
}
{{if .WithAuth}}
// WithJWTAuth sets the JWT service and optional blocklist for route protection.
// Call before registering routes:
//
//	h := handler.New{{.Name}}Handler(svc).WithJWTAuth(jwtSvc, cacheClient)
func (h *{{.Name}}Handler) WithJWTAuth(svc *jwtauth.Service, bl middleware.Blocklist) *{{.Name}}Handler {
	h.jwtSvc = svc
	h.blocklist = bl
	return h
}
{{end}}

// Routes returns a Chi router with all {{.NameLower}} endpoints.
// Register in main.go: r.Mount("/api/v1/{{.NamePlural}}", {{.NameLower}}Handler.Routes())
func (h *{{.Name}}Handler) Routes() chi.Router {
	r := chi.NewRouter()
{{- if .WithAuth}}
	// Authentication required for all {{.NameLower}} routes
	r.Use(middleware.JWTAuth(h.jwtSvc, h.blocklist))
{{- end}}
{{- if .AdminOnly}}
	// Admin-only access
	r.Use(middleware.RequireRole("admin"))
{{- end}}
	r.Post("/", h.Create{{.Name}})
	r.Get("/", h.List{{.Name}}s)
	r.Get("/{id}", h.Get{{.Name}})
	r.Put("/{id}", h.Update{{.Name}})
	r.Delete("/{id}", h.Delete{{.Name}})
	return r
}

// create{{.Name}}Request is the POST request body.
type create{{.Name}}Request struct {
{{- range .Fields}}
	{{title .Name}} {{.Type}} {{bt}}json:"{{.NameSnake}}"{{bt}}
{{- end}}
}

// {{.NameLower}}Response is the API response shape.
type {{.NameLower}}Response struct {
	ID        string {{bt}}json:"id"{{bt}}
{{- range .Fields}}
	{{title .Name}} {{.Type}} {{bt}}json:"{{.NameSnake}}"{{bt}}
{{- end}}
	CreatedAt string {{bt}}json:"created_at"{{bt}}
	UpdatedAt string {{bt}}json:"updated_at"{{bt}}
}

func to{{.Name}}Response(e *domain.{{.Name}}) *{{.NameLower}}Response {
	return &{{.NameLower}}Response{
		ID: e.ID.String(),
{{- range .Fields}}
		{{title .Name}}: e.{{title .Name}},
{{- end}}
		CreatedAt: e.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt: e.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
}

func (h *{{.Name}}Handler) Create{{.Name}}(w http.ResponseWriter, r *http.Request) {
	var req create{{.Name}}Request
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.Create{{.Name}}(r.Context(), domain.Create{{.Name}}Input{
{{- range .Fields}}
		{{title .Name}}: req.{{title .Name}},
{{- end}}
	})
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusCreated, to{{.Name}}Response(result))
}

func (h *{{.Name}}Handler) Get{{.Name}}(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	result, err := h.svc.Get{{.Name}}(r.Context(), id)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, to{{.Name}}Response(result))
}

func (h *{{.Name}}Handler) Update{{.Name}}(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	var req domain.Update{{.Name}}Input
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid JSON body"))
		return
	}
	result, err := h.svc.Update{{.Name}}(r.Context(), id, req)
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	middleware.WriteJSON(w, http.StatusOK, to{{.Name}}Response(result))
}

func (h *{{.Name}}Handler) Delete{{.Name}}(w http.ResponseWriter, r *http.Request) {
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		middleware.WriteError(w, apperror.ErrInvalidInput.WithMessage("invalid UUID"))
		return
	}
	if err := h.svc.Delete{{.Name}}(r.Context(), id); err != nil {
		middleware.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *{{.Name}}Handler) List{{.Name}}s(w http.ResponseWriter, r *http.Request) {
	results, total, err := h.svc.List{{.Name}}s(r.Context(), domain.DefaultPagination())
	if err != nil {
		middleware.WriteError(w, err)
		return
	}
	data := make([]*{{.NameLower}}Response, len(results))
	for i, e := range results {
		data[i] = to{{.Name}}Response(e)
	}
	middleware.WriteJSON(w, http.StatusOK, map[string]any{"data": data, "total": total})
}
`

// ── Handler test template ─────────────────────────────────────────────────────

var handlerTestTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package handler_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/internal/handler"
)

type mock{{.Name}}Svc struct{}

func (m *mock{{.Name}}Svc) Create{{.Name}}(_ context.Context, _ domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: uuid.New()}, nil
}
func (m *mock{{.Name}}Svc) Get{{.Name}}(_ context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Svc) Update{{.Name}}(_ context.Context, id uuid.UUID, _ domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Svc) Delete{{.Name}}(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mock{{.Name}}Svc) List{{.Name}}s(_ context.Context, _ domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	return []*domain.{{.Name}}{}, 0, nil
}

// setup{{.Name}}Router mounts the handler on a bare chi router — no JWT middleware.
// Unit tests exercise handler logic in isolation; auth is tested separately.
func setup{{.Name}}Router() *chi.Mux {
	h := handler.New{{.Name}}Handler(&mock{{.Name}}Svc{})
	r := chi.NewRouter()
	// Mount handlers directly (bypass JWTAuth — tested separately in middleware tests)
	r.Get("/api/v1/{{.NamePlural}}/{id}", h.Get{{.Name}})
	r.Put("/api/v1/{{.NamePlural}}/{id}", h.Update{{.Name}})
	r.Delete("/api/v1/{{.NamePlural}}/{id}", h.Delete{{.Name}})
	r.Get("/api/v1/{{.NamePlural}}", h.List{{.Name}}s)
	r.Post("/api/v1/{{.NamePlural}}", h.Create{{.Name}})
	return r
}

func Test{{.Name}}_Get_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/{{.NamePlural}}/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setup{{.Name}}Router().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}

func Test{{.Name}}_Delete_204(t *testing.T) {
	req := httptest.NewRequest(http.MethodDelete, "/api/v1/{{.NamePlural}}/"+uuid.New().String(), nil)
	rec := httptest.NewRecorder()
	setup{{.Name}}Router().ServeHTTP(rec, req)
	if rec.Code != http.StatusNoContent {
		t.Errorf("status = %d, want 204", rec.Code)
	}
}

func Test{{.Name}}_List_200(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/api/v1/{{.NamePlural}}", nil)
	rec := httptest.NewRecorder()
	setup{{.Name}}Router().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
}
`

// ── Service template ──────────────────────────────────────────────────────────

var serviceTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/pkg/apperror"
	"{{.Module}}/pkg/logger"
)

// {{.Name}}Service implements domain.{{.Name}}Service.
type {{.Name}}Service struct {
	repo domain.{{.Name}}Repository
}

// New{{.Name}}Service creates a new {{.Name}}Service.
func New{{.Name}}Service(repo domain.{{.Name}}Repository) domain.{{.Name}}Service {
	return &{{.Name}}Service{repo: repo}
}

func (s *{{.Name}}Service) Create{{.Name}}(ctx context.Context, input domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	result, err := s.repo.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("{{.Name}}Service.Create: %w", err)
	}
	logger.FromCtx(ctx).Info("{{.NameLower}} created", "id", result.ID)
	return result, nil
}

func (s *{{.Name}}Service) Get{{.Name}}(ctx context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	return s.repo.GetByID(ctx, id)
}

func (s *{{.Name}}Service) Update{{.Name}}(ctx context.Context, id uuid.UUID, input domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return nil, err
	}
	result, err := s.repo.Update(ctx, id, input)
	if err != nil {
		return nil, fmt.Errorf("{{.Name}}Service.Update: %w", err)
	}
	return result, nil
}

func (s *{{.Name}}Service) Delete{{.Name}}(ctx context.Context, id uuid.UUID) error {
	if _, err := s.repo.GetByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

func (s *{{.Name}}Service) List{{.Name}}s(ctx context.Context, p domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	if err := p.Validate(); err != nil {
		return nil, 0, apperror.ErrInvalidInput.WithMessage(err.Error())
	}
	return s.repo.List(ctx, p)
}
`

// ── Service test template ─────────────────────────────────────────────────────

var serviceTestTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"{{.Module}}/internal/domain"
	"{{.Module}}/internal/service"
)

type mock{{.Name}}Repo struct{}

func (m *mock{{.Name}}Repo) Create(_ context.Context, _ domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: uuid.New()}, nil
}
func (m *mock{{.Name}}Repo) GetByID(_ context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Repo) Update(_ context.Context, id uuid.UUID, _ domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	return &domain.{{.Name}}{ID: id}, nil
}
func (m *mock{{.Name}}Repo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mock{{.Name}}Repo) List(_ context.Context, _ domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	return []*domain.{{.Name}}{}, 0, nil
}

func TestCreate{{.Name}}_HappyPath(t *testing.T) {
	svc := service.New{{.Name}}Service(&mock{{.Name}}Repo{})
	result, err := svc.Create{{.Name}}(context.Background(), domain.Create{{.Name}}Input{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDelete{{.Name}}_HappyPath(t *testing.T) {
	svc := service.New{{.Name}}Service(&mock{{.Name}}Repo{})
	if err := svc.Delete{{.Name}}(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
`

// ── Repository template ───────────────────────────────────────────────────────

var repoTmpl = `// Code generated by axe on {{.Date}}.
// IMPLEMENT: complete after running: go generate ./ent/...
package repository

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	ent "{{.Module}}/ent"
	"{{.Module}}/internal/domain"
	"{{.Module}}/pkg/apperror"
)

// {{.Name}}Repo implements domain.{{.Name}}Repository using Ent.
type {{.Name}}Repo struct {
	client *ent.Client
}

// New{{.Name}}Repo creates a new {{.Name}}Repo.
func New{{.Name}}Repo(client *ent.Client) domain.{{.Name}}Repository {
	return &{{.Name}}Repo{client: client}
}

func (r *{{.Name}}Repo) Create(ctx context.Context, input domain.Create{{.Name}}Input) (*domain.{{.Name}}, error) {
	// IMPLEMENT: r.client.{{.Name}}.Create().Set...Save(ctx)
	return nil, fmt.Errorf("{{.Name}}Repo.Create: not implemented — run go generate ./ent/... first")
}

func (r *{{.Name}}Repo) GetByID(ctx context.Context, id uuid.UUID) (*domain.{{.Name}}, error) {
	// IMPLEMENT: r.client.{{.Name}}.Query().Where(...).Only(ctx)
	return nil, apperror.ErrNotFound.WithMessage("{{.NameLower}} not found")
}

func (r *{{.Name}}Repo) Update(ctx context.Context, id uuid.UUID, _ domain.Update{{.Name}}Input) (*domain.{{.Name}}, error) {
	// IMPLEMENT: r.client.{{.Name}}.UpdateOneID(id).Set...Save(ctx)
	return nil, fmt.Errorf("{{.Name}}Repo.Update: not implemented")
}

func (r *{{.Name}}Repo) Delete(ctx context.Context, id uuid.UUID) error {
	// IMPLEMENT: soft-delete or hard-delete
	return fmt.Errorf("{{.Name}}Repo.Delete: not implemented")
}

func (r *{{.Name}}Repo) List(ctx context.Context, p domain.Pagination) ([]*domain.{{.Name}}, int, error) {
	// IMPLEMENT: paginated query
	return []*domain.{{.Name}}{}, 0, nil
}
`

// ── Ent schema template ───────────────────────────────────────────────────────

var entSchemaTmpl = `// Code generated by axe on {{.Date}}.
// After editing: go generate ./ent/...
package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// {{.Name}} holds the schema definition for the {{.Name}} entity.
type {{.Name}} struct {
	ent.Schema
}

// Fields defines {{.Name}} entity fields.
func ({{.Name}}) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable(),
{{- range .Fields}}
		{{.EntType}}("{{.NameSnake}}"),
{{- end}}
{{- if .BelongsTo}}
		field.UUID("{{snake .BelongsTo}}_id", uuid.UUID{}),
{{- end}}
		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}
}

// Edges defines {{.Name}} entity relationships.
func ({{.Name}}) Edges() []ent.Edge {
	return nil
}
`

// ── SQL query template ────────────────────────────────────────────────────────

var sqlQueryTmpl = `-- {{.Name}} queries for sqlc — Generated: {{.Date}}

-- name: Get{{.Name}}ByID :one
SELECT id,{{range .Fields}} {{.NameSnake}},{{end}} created_at, updated_at
FROM {{.NamePlural}}
WHERE id = $1
LIMIT 1;

-- name: List{{.Name}}s :many
SELECT id,{{range .Fields}} {{.NameSnake}},{{end}} created_at, updated_at
FROM {{.NamePlural}}
ORDER BY created_at DESC
LIMIT $1 OFFSET $2;

-- name: Count{{.Name}}s :one
SELECT COUNT(*) FROM {{.NamePlural}};
`

// ── Migration template ────────────────────────────────────────────────────────

var migrationTmpl = `-- Migration: Create {{.NamePlural}} table — Generated: {{.Date}}

CREATE TABLE IF NOT EXISTS {{.NamePlural}} (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
{{- range .Fields}}
    {{.NameSnake}}    {{.SQLType}}    NOT NULL,
{{- end}}
{{- if .BelongsTo}}
    {{snake .BelongsTo}}_id UUID NOT NULL REFERENCES {{snake .BelongsTo}}s(id),
{{- end}}
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_{{.NamePlural}}_created ON {{.NamePlural}}(created_at DESC);

CREATE OR REPLACE TRIGGER set_{{.NamePlural}}_updated_at
    BEFORE UPDATE ON {{.NamePlural}}
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated_at();
`

// ── WebSocket handler template (--with-ws) ────────────────────────────────────

// wsHandlerTmpl generates a dedicated WebSocket room handler for the resource.
// The handler is intentionally separate from the REST handler so it can own the
// Hub dependency without polluting the conventional HTTP handler.
//
// Generated file: internal/handler/{name}_ws_handler.go
// Usage: hub.Join(client, "{{name}}") — one room per resource type by default.
var wsHandlerTmpl = `// Code generated by axe on {{.Date}}. Customize freely.
// WebSocket handler for the {{.Name}} resource (generated with --with-ws).
package handler

import (
	"net/http"

	"github.com/go-chi/chi/v5"

	"{{.Module}}/pkg/ws"
)

// {{.Name}}WSHandler handles WebSocket connections scoped to the {{.Name}} resource.
// Each connection joins the "{{.NameLower}}" room; all room members receive broadcasts.
//
// Wire up in main.go **after** registering WSAuth middleware on the router:
//
//	tracker := ws.NewUserConnTracker()
//	wsH := handler.New{{.Name}}WSHandler(hub)
//	r.With(ws.WSAuth(jwtSvc, cacheClient, tracker)).
//	    Mount("/ws/{{.NamePlural}}", wsH.Routes())
type {{.Name}}WSHandler struct {
	hub     *ws.Hub
	tracker *ws.UserConnTracker
}

// New{{.Name}}WSHandler creates a new {{.Name}}WSHandler backed by the given Hub.
// Pass a shared *ws.UserConnTracker (the same one supplied to WSAuth) so that
// connection-count accounting is consistent across REST and WS layers.
func New{{.Name}}WSHandler(hub *ws.Hub, tracker *ws.UserConnTracker) *{{.Name}}WSHandler {
	return &{{.Name}}WSHandler{hub: hub, tracker: tracker}
}

// Routes returns a Chi router exposing the WebSocket endpoint.
// Mount at: /ws/{{.NamePlural}}
func (h *{{.Name}}WSHandler) Routes() chi.Router {
	r := chi.NewRouter()
	// GET /ws/{{.NamePlural}} — upgrade and join the "{{.NameLower}}" room.
	r.Get("/", h.Connect)
	return r
}

// Connect performs the WebSocket upgrade and joins the client to the {{.Name}} room.
// Inbound messages from any member are broadcast to the entire room.
//
// IMPORTANT: This method MUST block (via <-client.Done()) until the peer disconnects.
// nhooyr.io/websocket closes the connection when the HTTP handler goroutine returns.
func (h *{{.Name}}WSHandler) Connect(w http.ResponseWriter, r *http.Request) {
	client, err := h.hub.UpgradeAuthenticated(w, r, h.tracker)
	if err != nil {
		// Hub already logged the error and wrote the HTTP error response.
		return
	}

	const room = "{{.NameLower}}"
	h.hub.Join(client, room)

	// Use hub.Context() — NOT r.Context() which is canceled when the HTTP handler returns.
	hubCtx := h.hub.Context()

	// Echo all inbound messages to the room (customize: persist, filter, route).
	client.OnMessage(func(msg []byte) {
		_ = h.hub.Broadcast(hubCtx, room, msg)
	})

	// Block until the client disconnects.
	// nhooyr.io/websocket requires the HTTP handler goroutine to stay alive.
	<-client.Done()
}
`


// ── pkg/ws package templates (scaffolded when --with-ws is used) ──────────────

// wsPkgAdapterTmpl — pkg/ws/adapter.go
var wsPkgAdapterTmpl = `package ws

import (
	"context"
)

// Adapter abstracts the pub/sub backend used by the Hub to fan out broadcast
// messages across multiple server instances.
//
// MemoryAdapter (default) is a no-op suitable for single-instance deployments.
// RedisAdapter enables cross-instance broadcasting via Redis Pub/Sub.
type Adapter interface {
	Publish(ctx context.Context, channel string, msg []byte) error
	Subscribe(ctx context.Context, channel string, handler func(msg []byte)) error
	Close() error
}

// MemoryAdapter is a no-op Adapter for single-instance deployments.
type MemoryAdapter struct{}

func (MemoryAdapter) Publish(_ context.Context, _ string, _ []byte) error  { return nil }
func (MemoryAdapter) Subscribe(_ context.Context, _ string, _ func([]byte)) error { return nil }
func (MemoryAdapter) Close() error                                          { return nil }
`

// wsPkgMetricsTmpl — pkg/ws/metrics.go
var wsPkgMetricsTmpl = `// Package ws provides a production-ready WebSocket hub for the axe framework.
package ws

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	wsActiveConnections = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "axe",
		Subsystem: "ws",
		Name:      "active_connections",
		Help:      "Number of currently active WebSocket connections.",
	})

	wsMessagesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "axe",
		Subsystem: "ws",
		Name:      "messages_total",
		Help:      "Total number of WebSocket messages handled by the hub.",
	}, []string{"direction"})

	wsRoomsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "axe",
		Subsystem: "ws",
		Name:      "rooms_active",
		Help:      "Number of currently active WebSocket rooms.",
	})

	wsConnectRejectedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "axe",
		Subsystem: "ws",
		Name:      "connect_rejected_total",
		Help:      "Total number of rejected WebSocket upgrade attempts.",
	})
)
`

// wsPkgRoomTmpl — pkg/ws/room.go
var wsPkgRoomTmpl = `package ws

import (
	"sync"
)

// Room is a named group of connected WebSocket clients.
// All methods are safe for concurrent use.
type Room struct {
	id      string
	clients map[string]*Client
	mu      sync.RWMutex
}

func newRoom(id string) *Room {
	return &Room{
		id:      id,
		clients: make(map[string]*Client),
	}
}

func (r *Room) add(c *Client) {
	r.mu.Lock()
	r.clients[c.id] = c
	r.mu.Unlock()
}

func (r *Room) remove(clientID string) {
	r.mu.Lock()
	delete(r.clients, clientID)
	r.mu.Unlock()
}

func (r *Room) broadcast(msg []byte) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	for _, c := range r.clients {
		c.send(msg)
	}
}

// Presence returns the IDs of all clients currently in the room.
func (r *Room) Presence() []string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	ids := make([]string, 0, len(r.clients))
	for id := range r.clients {
		ids = append(ids, id)
	}
	return ids
}

// Size returns the number of clients currently in the room.
func (r *Room) Size() int {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return len(r.clients)
}

func (r *Room) isEmpty() bool {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return len(r.clients) == 0
}
`

// wsPkgClientTmpl — pkg/ws/client.go
var wsPkgClientTmpl = `package ws

import (
	"context"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/google/uuid"
	"nhooyr.io/websocket"
)

const (
	sendBufSize  = 256
	writeTimeout = 10 * time.Second
	pingInterval = 30 * time.Second
)

// MessageHandler is called by the client when a message is received from the browser.
type MessageHandler func(msg []byte)

// Client wraps an nhooyr.io/websocket connection.
type Client struct {
	id     string
	UserID string

	conn   *websocket.Conn
	hub    *Hub
	sendCh chan []byte
	done   chan struct{} // closed when readPump exits; signals handler to return

	onMessage MessageHandler

	rooms map[string]struct{}
	mu    sync.RWMutex

	log *slog.Logger
}

func newClient(conn *websocket.Conn, hub *Hub) *Client {
	return newClientWithMeta(conn, hub, "")
}

func newClientWithMeta(conn *websocket.Conn, hub *Hub, userID string) *Client {
	return &Client{
		id:     uuid.New().String(),
		UserID: userID,
		conn:   conn,
		hub:    hub,
		sendCh: make(chan []byte, sendBufSize),
		done:   make(chan struct{}),
		rooms:  make(map[string]struct{}),
		log:    hub.log,
	}
}

// ID returns the unique identifier for this client.
func (c *Client) ID() string { return c.id }

// OnMessage registers a handler called for every message received from the peer.
func (c *Client) OnMessage(fn MessageHandler) {
	c.mu.Lock()
	c.onMessage = fn
	c.mu.Unlock()
}

func (c *Client) send(msg []byte) {
	select {
	case c.sendCh <- msg:
		wsMessagesTotal.WithLabelValues("outbound").Inc()
	default:
		c.log.Warn("ws: client send buffer full, dropping message", "client_id", c.id)
	}
}

// Close signals the client to disconnect gracefully.
func (c *Client) Close() {
	close(c.sendCh)
}

// Done returns a channel closed when the client disconnects.
// HTTP handlers should block on <-client.Done() to keep the WebSocket
// connection alive: nhooyr.io/websocket closes the connection when
// the handler's goroutine returns.
func (c *Client) Done() <-chan struct{} { return c.done }

func (c *Client) readPump(ctx context.Context) {
	defer func() {
		close(c.done)          // unblock handler goroutine
		c.hub.unregister <- c
	}()

	for {
		_, msg, err := c.conn.Read(ctx)
		if err != nil {
			if ctx.Err() == nil {
				c.log.Debug("ws: read error", "client_id", c.id, "error", err)
			}
			return
		}
		wsMessagesTotal.WithLabelValues("inbound").Inc()

		c.mu.RLock()
		handler := c.onMessage
		c.mu.RUnlock()

		if handler != nil {
			handler(msg)
		}
	}
}

func (c *Client) writePump(ctx context.Context) {
	ticker := time.NewTicker(pingInterval)
	defer ticker.Stop()

	for {
		select {
		case msg, ok := <-c.sendCh:
			if !ok {
				_ = c.conn.Close(websocket.StatusNormalClosure, "")
				return
			}
			writeCtx, cancel := context.WithTimeout(ctx, writeTimeout)
			err := c.conn.Write(writeCtx, websocket.MessageText, msg)
			cancel()
			if err != nil {
				c.log.Debug("ws: write error", "client_id", c.id, "error", err)
				return
			}

		case <-ticker.C:
			pingCtx, cancel := context.WithTimeout(ctx, writeTimeout)
			err := c.conn.Ping(pingCtx)
			cancel()
			if err != nil {
				c.log.Debug("ws: ping error", "client_id", c.id, "error", err)
				return
			}

		case <-ctx.Done():
			return
		}
	}
}

func (c *Client) joinRoom(roomID string) {
	c.mu.Lock()
	c.rooms[roomID] = struct{}{}
	c.mu.Unlock()
}

func (c *Client) leaveRoom(roomID string) {
	c.mu.Lock()
	delete(c.rooms, roomID)
	c.mu.Unlock()
}

func (c *Client) allRooms() []string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	rooms := make([]string, 0, len(c.rooms))
	for id := range c.rooms {
		rooms = append(rooms, id)
	}
	return rooms
}

// String implements fmt.Stringer.
func (c *Client) String() string {
	return fmt.Sprintf("Client(%s)", c.id)
}
`

// wsPkgHubTmpl — pkg/ws/hub.go
var wsPkgHubTmpl = `// Package ws provides a production-ready WebSocket hub.
//
// Quick start:
//
//	hub := ws.NewHub()
//	ctx, cancel := context.WithCancel(context.Background())
//	defer cancel()
//	go hub.Run(ctx)
//
//	// In HTTP handler:
//	func (h *Handler) Connect(w http.ResponseWriter, r *http.Request) {
//	    client, err := hub.Upgrade(w, r)
//	    if err != nil { return }
//	    hub.Join(client, "general")
//	    client.OnMessage(func(msg []byte) {
//	        hub.Broadcast(context.Background(), "general", msg)
//	    })
//	}
package ws

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"sync"

	"nhooyr.io/websocket"
)

// Hub is the central WebSocket connection registry.
type Hub struct {
	clients    map[string]*Client
	rooms      map[string]*Room
	mu         sync.RWMutex
	register   chan *Client
	unregister chan *Client
	adapter    Adapter
	ctx        context.Context
	cancel     context.CancelFunc
	log        *slog.Logger
	pingInterval interface{} // reserved for future HubOption
}

// HubOption is a functional option for NewHub.
type HubOption func(*Hub)

// WithAdapter sets the pub/sub backend. Default: MemoryAdapter (single-instance).
func WithAdapter(a Adapter) HubOption {
	return func(h *Hub) { h.adapter = a }
}

// WithLogger sets the logger used by the hub and its clients.
func WithLogger(l *slog.Logger) HubOption {
	return func(h *Hub) { h.log = l }
}

// NewHub constructs a Hub with optional configuration.
func NewHub(opts ...HubOption) *Hub {
	ctx, cancel := context.WithCancel(context.Background())
	h := &Hub{
		clients:    make(map[string]*Client),
		rooms:      make(map[string]*Room),
		register:   make(chan *Client, 32),
		unregister: make(chan *Client, 32),
		adapter:    MemoryAdapter{},
		ctx:        ctx,
		cancel:     cancel,
		log:        slog.Default(),
	}
	for _, o := range opts {
		o(h)
	}
	return h
}

// Run starts the Hub event loop. It blocks until ctx is cancelled.
func (h *Hub) Run(ctx context.Context) {
	go func() {
		<-ctx.Done()
		h.cancel()
	}()

	for {
		select {
		case c := <-h.register:
			h.mu.Lock()
			h.clients[c.id] = c
			h.mu.Unlock()
			wsActiveConnections.Inc()
			h.log.Info("ws: client connected", "client_id", c.id)

		case c := <-h.unregister:
			h.mu.Lock()
			if _, ok := h.clients[c.id]; ok {
				for _, roomID := range c.allRooms() {
					if room, exists := h.rooms[roomID]; exists {
						room.remove(c.id)
						if room.isEmpty() {
							delete(h.rooms, roomID)
							wsRoomsActive.Dec()
							h.log.Debug("ws: room destroyed", "room", roomID)
						}
					}
				}
				delete(h.clients, c.id)
				wsActiveConnections.Dec()
				h.log.Info("ws: client disconnected", "client_id", c.id)
			}
			h.mu.Unlock()

		case <-h.ctx.Done():
			h.log.Info("ws: hub shutting down")
			h.mu.Lock()
			for _, c := range h.clients {
				c.Close()
			}
			h.clients = make(map[string]*Client)
			h.rooms = make(map[string]*Room)
			h.mu.Unlock()
			if err := h.adapter.Close(); err != nil {
				h.log.Warn("ws: adapter close error", "error", err)
			}
			return
		}
	}
}

// Upgrade performs the HTTP → WebSocket handshake and registers the client.
func (h *Hub) Upgrade(w http.ResponseWriter, r *http.Request) (*Client, error) {
	conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{
		InsecureSkipVerify: true,
	})
	if err != nil {
		wsConnectRejectedTotal.Inc()
		h.log.Warn("ws: upgrade failed", "error", err, "remote", r.RemoteAddr)
		return nil, fmt.Errorf("ws: upgrade: %w", err)
	}

	c := newClient(conn, h)
	h.register <- c

	clientCtx, clientCancel := context.WithCancel(h.ctx)
	go func() {
		defer clientCancel()
		c.writePump(clientCtx)
	}()
	go c.readPump(clientCtx)

	return c, nil
}

// UpgradeAuthenticated performs the WebSocket handshake for authenticated requests.
// It reads the userID from the context (injected by WSAuth middleware).
func (h *Hub) UpgradeAuthenticated(w http.ResponseWriter, r *http.Request, tracker *UserConnTracker) (*Client, error) {
	conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{
		InsecureSkipVerify: true,
	})
	if err != nil {
		wsConnectRejectedTotal.Inc()
		h.log.Warn("ws: upgrade failed", "error", err, "remote", r.RemoteAddr)
		return nil, fmt.Errorf("ws: upgrade: %w", err)
	}

	userID := ""
	if claims := ClaimsFromCtx(r.Context()); claims != nil {
		userID = claims.UserID
	}

	c := newClientWithMeta(conn, h, userID)
	h.register <- c

	clientCtx, clientCancel := context.WithCancel(h.ctx)
	go func() {
		defer clientCancel()
		c.writePump(clientCtx)
	}()
	go func() {
		c.readPump(clientCtx)
		if tracker != nil && userID != "" {
			tracker.Release(userID)
			h.log.Debug("ws: conn slot released", "user_id", userID)
		}
	}()

	return c, nil
}

// Join adds client to the named room, creating the room if necessary.
func (h *Hub) Join(client *Client, roomID string) {
	h.mu.Lock()
	room, exists := h.rooms[roomID]
	if !exists {
		room = newRoom(roomID)
		h.rooms[roomID] = room
		wsRoomsActive.Inc()
		h.log.Debug("ws: room created", "room", roomID)

		_ = h.adapter.Subscribe(h.ctx, roomID, func(msg []byte) {
			h.mu.RLock()
			r, ok := h.rooms[roomID]
			h.mu.RUnlock()
			if ok {
				r.broadcast(msg)
			}
		})
	}
	room.add(client)
	h.mu.Unlock()

	client.joinRoom(roomID)
	h.log.Debug("ws: client joined room", "client_id", client.id, "room", roomID)
}

// Leave removes client from the named room.
func (h *Hub) Leave(client *Client, roomID string) {
	h.mu.Lock()
	if room, ok := h.rooms[roomID]; ok {
		room.remove(client.id)
		if room.isEmpty() {
			delete(h.rooms, roomID)
			wsRoomsActive.Dec()
			h.log.Debug("ws: room destroyed", "room", roomID)
		}
	}
	h.mu.Unlock()

	client.leaveRoom(roomID)
	h.log.Debug("ws: client left room", "client_id", client.id, "room", roomID)
}

// Broadcast sends msg to all clients in roomID on this instance and publishes
// it to the adapter so that other instances also deliver it.
func (h *Hub) Broadcast(ctx context.Context, roomID string, msg []byte) error {
	h.mu.RLock()
	room, ok := h.rooms[roomID]
	h.mu.RUnlock()
	if ok {
		room.broadcast(msg)
	}

	if err := h.adapter.Publish(ctx, roomID, msg); err != nil {
		return fmt.Errorf("ws: broadcast to %q: %w", roomID, err)
	}
	return nil
}

// Presence returns the IDs of all clients in roomID.
func (h *Hub) Presence(roomID string) []string {
	h.mu.RLock()
	room, ok := h.rooms[roomID]
	h.mu.RUnlock()
	if !ok {
		return nil
	}
	return room.Presence()
}

// ClientCount returns the total number of connected clients.
func (h *Hub) ClientCount() int {
	h.mu.RLock()
	defer h.mu.RUnlock()
	return len(h.clients)
}

// Shutdown stops the hub gracefully.
func (h *Hub) Shutdown() {
	h.cancel()
}

// Context returns the hub's lifecycle context.
// Use this in OnMessage callbacks instead of r.Context() — the HTTP request
// context is canceled when the handler returns, which would cancel broadcasts.
func (h *Hub) Context() context.Context { return h.ctx }

// RoomSize returns the number of clients currently in roomID.
func (h *Hub) RoomSize(roomID string) int {
	h.mu.RLock()
	room, ok := h.rooms[roomID]
	h.mu.RUnlock()
	if !ok {
		return 0
	}
	return room.Size()
}
`

// wsPkgAuthTmpl — pkg/ws/auth.go
// Note: {{.Module}} is substituted at generation time.
var wsPkgAuthTmpl = `package ws

import (
	"context"
	"net/http"
	"strings"
	"sync"
	"sync/atomic"

	"{{.Module}}/pkg/jwtauth"
	"{{.Module}}/pkg/logger"
)

type wsContextKey string

const wsClaimsKey wsContextKey = "ws_jwt_claims"

// WSBlocklist defines the contract to check token revocation.
type WSBlocklist interface {
	IsTokenBlocked(ctx context.Context, jti string) (bool, error)
}

// ClaimsFromCtx retrieves JWT claims stored by WSAuth middleware.
func ClaimsFromCtx(ctx context.Context) *jwtauth.Claims {
	v, _ := ctx.Value(wsClaimsKey).(*jwtauth.Claims)
	return v
}

type authOptions struct {
	maxConns int
}

// AuthOption configures WSAuth behaviour.
type AuthOption func(*authOptions)

// WithMaxConnsPerUser sets the per-user WebSocket connection cap. Default: 5.
func WithMaxConnsPerUser(n int) AuthOption {
	return func(o *authOptions) {
		if n > 0 {
			o.maxConns = n
		}
	}
}

// UserConnTracker tracks the number of active WebSocket connections per user.
type UserConnTracker struct {
	m sync.Map // map[userID string]*int64
}

// NewUserConnTracker creates an empty tracker.
func NewUserConnTracker() *UserConnTracker { return &UserConnTracker{} }

// Acquire tries to increment the connection count for userID.
func (t *UserConnTracker) Acquire(userID string, max int) bool {
	actual, _ := t.m.LoadOrStore(userID, new(int64))
	counter := actual.(*int64)

	for {
		cur := atomic.LoadInt64(counter)
		if cur >= int64(max) {
			return false
		}
		if atomic.CompareAndSwapInt64(counter, cur, cur+1) {
			return true
		}
	}
}

// Release decrements the connection count for userID.
func (t *UserConnTracker) Release(userID string) {
	if v, ok := t.m.Load(userID); ok {
		counter := v.(*int64)
		if atomic.AddInt64(counter, -1) < 0 {
			atomic.StoreInt64(counter, 0)
		}
	}
}

// Count returns the current active connection count for userID.
func (t *UserConnTracker) Count(userID string) int64 {
	v, ok := t.m.Load(userID)
	if !ok {
		return 0
	}
	return atomic.LoadInt64(v.(*int64))
}

// WSAuth returns an HTTP middleware that validates a JWT for WebSocket upgrade requests.
// The token is read from:
//  1. Authorization: Bearer <token>
//  2. ?token=<jwt>  (required by browser WebSocket clients)
func WSAuth(
	svc *jwtauth.Service,
	blocklist WSBlocklist,
	tracker *UserConnTracker,
	opts ...AuthOption,
) func(http.Handler) http.Handler {
	options := &authOptions{maxConns: 5}
	for _, o := range opts {
		o(options)
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			log := logger.FromCtx(r.Context())

			token := extractWSToken(r)
			if token == "" {
				log.Info("ws auth: missing token", "remote", r.RemoteAddr)
				http.Error(w, "missing token", http.StatusUnauthorized)
				wsConnectRejectedTotal.Inc()
				return
			}

			claims, err := svc.Validate(token)
			if err != nil {
				log.Info("ws auth: invalid token", "remote", r.RemoteAddr, "error", err)
				http.Error(w, "invalid or expired token", http.StatusUnauthorized)
				wsConnectRejectedTotal.Inc()
				return
			}

			if blocklist != nil && claims.JTI() != "" {
				blocked, blErr := blocklist.IsTokenBlocked(r.Context(), claims.JTI())
				if blErr != nil {
					log.Warn("ws auth: blocklist check failed", "error", blErr)
				} else if blocked {
					log.Info("ws auth: token revoked", "jti", claims.JTI(), "user_id", claims.UserID)
					http.Error(w, "token revoked", http.StatusUnauthorized)
					wsConnectRejectedTotal.Inc()
					return
				}
			}

			if tracker != nil {
				if !tracker.Acquire(claims.UserID, options.maxConns) {
					log.Warn("ws auth: connection limit reached",
						"user_id", claims.UserID,
						"max", options.maxConns,
						"current", tracker.Count(claims.UserID))
					http.Error(w, "too many connections", http.StatusTooManyRequests)
					wsConnectRejectedTotal.Inc()
					return
				}
			}

			ctx := context.WithValue(r.Context(), wsClaimsKey, claims)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

func extractWSToken(r *http.Request) string {
	if h := r.Header.Get("Authorization"); h != "" {
		parts := strings.SplitN(h, " ", 2)
		if len(parts) == 2 && strings.EqualFold(parts[0], "Bearer") {
			if t := strings.TrimSpace(parts[1]); t != "" {
				return t
			}
		}
	}
	if t := r.URL.Query().Get("token"); t != "" {
		return t
	}
	return ""
}
`

// wsPkgRedisAdapterTmpl — pkg/ws/redis_adapter.go
var wsPkgRedisAdapterTmpl = `package ws

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/redis/go-redis/v9"
)

// RedisAdapter implements the Adapter interface using Redis Pub/Sub.
type RedisAdapter struct {
	rdb    *redis.Client
	prefix string
	log    *slog.Logger
	pubsubs map[string]*redis.PubSub
}

// NewRedisAdapter creates a RedisAdapter that uses the given go-redis client.
func NewRedisAdapter(rdb *redis.Client, opts ...func(*RedisAdapter)) *RedisAdapter {
	a := &RedisAdapter{
		rdb:     rdb,
		prefix:  "axe:ws:",
		log:     slog.Default(),
		pubsubs: make(map[string]*redis.PubSub),
	}
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithRedisPrefix overrides the default channel prefix.
func WithRedisPrefix(p string) func(*RedisAdapter) {
	return func(a *RedisAdapter) { a.prefix = p }
}

// WithRedisLogger overrides the default logger.
func WithRedisLogger(l *slog.Logger) func(*RedisAdapter) {
	return func(a *RedisAdapter) { a.log = l }
}

func (a *RedisAdapter) channel(ch string) string { return a.prefix + ch }

// Publish sends msg to all instances subscribed to channel.
func (a *RedisAdapter) Publish(ctx context.Context, channel string, msg []byte) error {
	if err := a.rdb.Publish(ctx, a.channel(channel), msg).Err(); err != nil {
		return fmt.Errorf("ws/redis: publish to %q: %w", channel, err)
	}
	return nil
}

// Subscribe registers handler to receive every message on channel.
func (a *RedisAdapter) Subscribe(ctx context.Context, channel string, handler func([]byte)) error {
	ch := a.channel(channel)
	ps := a.rdb.Subscribe(ctx, ch)

	if _, err := ps.Receive(ctx); err != nil {
		ps.Close() //nolint:errcheck
		return fmt.Errorf("ws/redis: subscribe to %q: %w", channel, err)
	}

	a.pubsubs[channel] = ps

	go func() {
		defer ps.Close() //nolint:errcheck
		msgCh := ps.Channel()
		for {
			select {
			case msg, ok := <-msgCh:
				if !ok {
					return
				}
				handler([]byte(msg.Payload))
			case <-ctx.Done():
				return
			}
		}
	}()

	a.log.Info("ws/redis: subscribed", "channel", ch)
	return nil
}

// Close unsubscribes from all channels and releases resources.
func (a *RedisAdapter) Close() error {
	var errs []error
	for ch, ps := range a.pubsubs {
		if err := ps.Unsubscribe(context.Background(), a.channel(ch)); err != nil {
			errs = append(errs, err)
		}
		if err := ps.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("ws/redis: close errors: %v", errs)
	}
	return nil
}
`
