// Code generated by axe on 2026-04-15. Customize freely.
package service_test

import (
	"context"
	"testing"

	"github.com/google/uuid"

	"github.com/axe-go/axe/internal/domain"
	"github.com/axe-go/axe/internal/service"
)

type mockPostRepo struct{}

func (m *mockPostRepo) Create(_ context.Context, _ domain.CreatePostInput) (*domain.Post, error) {
	return &domain.Post{ID: uuid.New()}, nil
}
func (m *mockPostRepo) GetByID(_ context.Context, id uuid.UUID) (*domain.Post, error) {
	return &domain.Post{ID: id}, nil
}
func (m *mockPostRepo) Update(_ context.Context, id uuid.UUID, _ domain.UpdatePostInput) (*domain.Post, error) {
	return &domain.Post{ID: id}, nil
}
func (m *mockPostRepo) Delete(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockPostRepo) List(_ context.Context, _ domain.Pagination) ([]*domain.Post, int, error) {
	return []*domain.Post{}, 0, nil
}

func TestCreatePost_HappyPath(t *testing.T) {
	svc := service.NewPostService(&mockPostRepo{})
	result, err := svc.CreatePost(context.Background(), domain.CreatePostInput{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("result should not be nil")
	}
}

func TestDeletePost_HappyPath(t *testing.T) {
	svc := service.NewPostService(&mockPostRepo{})
	if err := svc.DeletePost(context.Background(), uuid.New()); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
