// Code generated by axe on 2026-04-19.
// After editing: go generate ./ent/...
package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// Series holds the schema definition for the Series entity.
type Series struct {
	ent.Schema
}

// Fields defines Series entity fields.
func (Series) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable(),
		field.String("title"),
		field.String("description"),
		field.String("genre"),
		field.String("author"),
		field.String("cover_url"),
		field.String("status"),
		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}
}

// Edges defines Series entity relationships.
func (Series) Edges() []ent.Edge {
	return nil
}
