// Code generated by axe on 2026-04-15. Customize freely.
package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Post is the Post domain entity.
type Post struct {
	ID uuid.UUID
	Title string
	Body string
	Published bool
	Views int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// PostRepository defines data access for Post.
// Implemented in internal/repository/post_repo.go.
type PostRepository interface {
	Create(ctx context.Context, input CreatePostInput) (*Post, error)
	Update(ctx context.Context, id uuid.UUID, input UpdatePostInput) (*Post, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetByID(ctx context.Context, id uuid.UUID) (*Post, error)
	List(ctx context.Context, pagination Pagination) ([]*Post, int, error)
}

// PostService defines business operations for Post.
// Implemented in internal/service/post_service.go.
type PostService interface {
	CreatePost(ctx context.Context, input CreatePostInput) (*Post, error)
	GetPost(ctx context.Context, id uuid.UUID) (*Post, error)
	UpdatePost(ctx context.Context, id uuid.UUID, input UpdatePostInput) (*Post, error)
	DeletePost(ctx context.Context, id uuid.UUID) error
	ListPosts(ctx context.Context, pagination Pagination) ([]*Post, int, error)
}

// CreatePostInput holds fields required to create a Post.
type CreatePostInput struct {
	Title string
	Body string
	Published bool
	Views int64
}

// UpdatePostInput holds optional fields for partial update.
type UpdatePostInput struct {
	Title *string
	Body *string
	Published *bool
	Views *int64
}
